/*
 * Copyright (c) 2025 SAP SE or an SAP affiliate company. All rights reserved.
 */

/*
 * Soda Store API
 * API for managing sodas in a soda store
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package test;

import java.util.Objects;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.List;
import test.Cola;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.google.common.annotations.Beta;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * FantaFlavor
 */
@Beta
public interface FantaFlavor  {
    /**
     * Helper class to create a Cola that implements {@link FantaFlavor}.
     */
    record InnerCola(@com.fasterxml.jackson.annotation.JsonValue @Nonnull Cola value) implements FantaFlavor {}

    /**
     * Creator to enable deserialization of a Cola.
     *
     * @param val the value to use
     * @return a new instance of {@link InnerCola}.
     */
    @com.fasterxml.jackson.annotation.JsonCreator
    @Nonnull
    static InnerCola create( @Nonnull final Cola val) { return new InnerCola(val); }

    /**
     * Helper class to create a String that implements {@link FantaFlavor}.
     */
    record InnerString(@com.fasterxml.jackson.annotation.JsonValue @Nonnull String value) implements FantaFlavor {}

    /**
     * Creator to enable deserialization of a String.
     *
     * @param val the value to use
     * @return a new instance of {@link InnerString}.
     */
    @com.fasterxml.jackson.annotation.JsonCreator
    @Nonnull
    static InnerString create( @Nonnull final String val) { return new InnerString(val); }

    /**
    * Helper class to create a list of String that implements {@link FantaFlavor}.
    */
    record InnerStrings(@com.fasterxml.jackson.annotation.JsonValue @Nonnull List<String> values) implements FantaFlavor {}

    /**
    * Creator to enable deserialization of a list of String.
    *
    * @param val the value to use
    * @return a new instance of {@link InnerStrings}.
    */
    @com.fasterxml.jackson.annotation.JsonCreator
    @Nonnull
    static InnerStrings create( @Nonnull final List<String> val) { return new InnerStrings(val); }

}

