name: "Stash SDK Targets"
description: "Stashes the SDK target directories"

inputs:
  sdk-root:
    description: "The root directory of the SDK"
    required: false
    default: "."
  key:
    description: "The key to use when stashing the SDK target directories"
    required: false
    default: "sdk-targets-${{ github.ref }}"
  force-update:
    description: "Overrides any existing stashes"
    required: false
    default: "true"
  update-after-days:
    description: "Overrides any existing stash IF the existing stash is older than the specified amount of days"
    required: false
    default: ""

outputs:
  stashed:
    description: "Whether the SDK target directories were stashed"
    value: ${{ steps.stash.outputs.stashed }}

runs:
  using: composite
  steps:
    - name: Print Action Start
      run: echo ">>>>> Starting Stash SDK Targets Action; inputs = ${{ toJson(inputs) }}"
      shell: bash

    - name: Stash
      id: stash
      uses: ./.github/actions/stash
      with:
        # NOTE: These paths must match the ones of the unstash action EXACTLY
        path: ${{ inputs.sdk-root }}/**/target/*
        key: ${{ inputs.key }}
        force-update: ${{ inputs.force-update }}
        update-after-days: ${{ inputs.update-after-days }}

    - name: Print Action End
      if: always()
      run: echo "<<<<< Finished Stash SDK Targets Action"
      shell: bash
