/*
 * Copyright (c) 2025 SAP SE or an SAP affiliate company. All rights reserved.
 */

/*
 * Azure OpenAI Service API
 * Azure OpenAI APIs for completions and search
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.cloud.sdk.services.openai.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.sap.cloud.sdk.services.openai.model.ChatCompletionNamedToolChoice;
import com.sap.cloud.sdk.services.openai.model.ChatCompletionNamedToolChoiceFunction;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * Controls which (if any) tool is called by the model. &#x60;none&#x60; means the model will not call any tool and instead generates a message. &#x60;auto&#x60; means the model can pick between generating a message or calling one or more tools. &#x60;required&#x60; means the model must call one or more tools. Specifying a particular tool via &#x60;{\&quot;type\&quot;: \&quot;function\&quot;, \&quot;function\&quot;: {\&quot;name\&quot;: \&quot;my_function\&quot;}}&#x60; forces the model to call that tool. &#x60;none&#x60; is the default when no tools are present. &#x60;auto&#x60; is the default if tools are present. 
 */
// CHECKSTYLE:OFF
public class ChatCompletionToolChoiceOption 
// CHECKSTYLE:ON
{
  /**
   * The type of the tool. Currently, only &#x60;function&#x60; is supported.
   */
  public enum TypeEnum {
    /**
    * The FUNCTION option of this ChatCompletionToolChoiceOption
    */
    FUNCTION("function");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    /**
    * Get the value of the enum
    * @return The enum value
    */
    @JsonValue
    @Nonnull public String getValue() {
      return value;
    }

    /**
    * Get the String value of the enum value.
    * @return The enum value as String
    */
    @Override
    @Nonnull public String toString() {
      return String.valueOf(value);
    }

    /**
    * Get the enum value from a String value
    * @param value The String value
    * @return The enum value of type ChatCompletionToolChoiceOption
    */
    @JsonCreator
    @Nonnull public static TypeEnum fromValue(@Nonnull final String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  @JsonProperty("type")
  private TypeEnum type;

  @JsonProperty("function")
  private ChatCompletionNamedToolChoiceFunction function;

  @JsonAnySetter
  @JsonAnyGetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

  /**
   * Set the type of this {@link ChatCompletionToolChoiceOption} instance and return the same instance.
   *
   * @param type  The type of the tool. Currently, only &#x60;function&#x60; is supported.
   * @return The same instance of this {@link ChatCompletionToolChoiceOption} class
   */
  @Nonnull public ChatCompletionToolChoiceOption type( @Nonnull final TypeEnum type) {
    this.type = type;
    return this;
  }

  /**
   * The type of the tool. Currently, only &#x60;function&#x60; is supported.
   * @return type  The type of this {@link ChatCompletionToolChoiceOption} instance.
   */
  @Nonnull
  public TypeEnum getType() {
    return type;
  }

  /**
   * Set the type of this {@link ChatCompletionToolChoiceOption} instance.
   *
   * @param type  The type of the tool. Currently, only &#x60;function&#x60; is supported.
   */
  public void setType( @Nonnull final TypeEnum type) {
    this.type = type;
  }

  /**
   * Set the function of this {@link ChatCompletionToolChoiceOption} instance and return the same instance.
   *
   * @param function  The function of this {@link ChatCompletionToolChoiceOption}
   * @return The same instance of this {@link ChatCompletionToolChoiceOption} class
   */
  @Nonnull public ChatCompletionToolChoiceOption function( @Nonnull final ChatCompletionNamedToolChoiceFunction function) {
    this.function = function;
    return this;
  }

  /**
   * Get function
   * @return function  The function of this {@link ChatCompletionToolChoiceOption} instance.
   */
  @Nonnull
  public ChatCompletionNamedToolChoiceFunction getFunction() {
    return function;
  }

  /**
   * Set the function of this {@link ChatCompletionToolChoiceOption} instance.
   *
   * @param function  The function of this {@link ChatCompletionToolChoiceOption}
   */
  public void setFunction( @Nonnull final ChatCompletionNamedToolChoiceFunction function) {
    this.function = function;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link ChatCompletionToolChoiceOption}.
   * @return The set of properties names
   */
  @JsonIgnore
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of this {@link ChatCompletionToolChoiceOption} instance.
   * @deprecated Use {@link #toMap()} instead.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  @Deprecated
  public Object getCustomField( @Nonnull final String name ) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("ChatCompletionToolChoiceOption has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  /**
   * Get the value of all properties of this {@link ChatCompletionToolChoiceOption} instance including unrecognized properties.
   *
   * @return The map of all properties
   */
  @JsonIgnore
  @Nonnull
  public Map<String, Object> toMap()
  {
    final Map<String, Object> declaredFields = new LinkedHashMap<>(cloudSdkCustomFields);
    if( type != null ) declaredFields.put("type", type);
    if( function != null ) declaredFields.put("function", function);
    return declaredFields;
  }

  /**
   * Set an unrecognizable property of this {@link ChatCompletionToolChoiceOption} instance. If the map previously contained a mapping
   * for the key, the old value is replaced by the specified value.
   * @param customFieldName The name of the property
   * @param customFieldValue The value of the property
   */
  @JsonIgnore
  public void setCustomField( @Nonnull String customFieldName, @Nullable Object customFieldValue )
  {
      cloudSdkCustomFields.put(customFieldName, customFieldValue);
  }


  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final ChatCompletionToolChoiceOption chatCompletionToolChoiceOption = (ChatCompletionToolChoiceOption) o;
    return Objects.equals(this.cloudSdkCustomFields, chatCompletionToolChoiceOption.cloudSdkCustomFields) &&
        Objects.equals(this.type, chatCompletionToolChoiceOption.type) &&
        Objects.equals(this.function, chatCompletionToolChoiceOption.function);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, function, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class ChatCompletionToolChoiceOption {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    function: ").append(toIndentedString(function)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

