/*
 * Copyright (c) 2025 SAP SE or an SAP affiliate company. All rights reserved.
 */

/*
 * Azure OpenAI Service API
 * Azure OpenAI APIs for completions and search
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.cloud.sdk.services.openai.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.sap.cloud.sdk.services.openai.model.OnYourDataAuthenticationType;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * The authentication options for Azure OpenAI On Your Data.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "type", visible = true)
@JsonSubTypes({
  @JsonSubTypes.Type(value = OnYourDataApiKeyAuthenticationOptions.class, name = "api_key"),
  @JsonSubTypes.Type(value = OnYourDataConnectionStringAuthenticationOptions.class, name = "connection_string"),
  @JsonSubTypes.Type(value = OnYourDataSystemAssignedManagedIdentityAuthenticationOptions.class, name = "system_assigned_managed_identity"),
  @JsonSubTypes.Type(value = OnYourDataUserAssignedManagedIdentityAuthenticationOptions.class, name = "user_assigned_managed_identity"),
})
// CHECKSTYLE:OFF
public class OnYourDataAuthenticationOptions 
// CHECKSTYLE:ON
{
  @JsonProperty("type")
  protected OnYourDataAuthenticationType type;

  @JsonAnySetter
  @JsonAnyGetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

  /**
   * Set the type of this {@link OnYourDataAuthenticationOptions} instance and return the same instance.
   *
   * @param type  The type of this {@link OnYourDataAuthenticationOptions}
   * @return The same instance of this {@link OnYourDataAuthenticationOptions} class
   */
  @Nonnull public OnYourDataAuthenticationOptions type( @Nonnull final OnYourDataAuthenticationType type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type  The type of this {@link OnYourDataAuthenticationOptions} instance.
   */
  @Nonnull
  public OnYourDataAuthenticationType getType() {
    return type;
  }

  /**
   * Set the type of this {@link OnYourDataAuthenticationOptions} instance.
   *
   * @param type  The type of this {@link OnYourDataAuthenticationOptions}
   */
  public void setType( @Nonnull final OnYourDataAuthenticationType type) {
    this.type = type;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link OnYourDataAuthenticationOptions}.
   * @return The set of properties names
   */
  @JsonIgnore
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of this {@link OnYourDataAuthenticationOptions} instance.
   * @deprecated Use {@link #toMap()} instead.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  @Deprecated
  public Object getCustomField( @Nonnull final String name ) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("OnYourDataAuthenticationOptions has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  /**
   * Get the value of all properties of this {@link OnYourDataAuthenticationOptions} instance including unrecognized properties.
   *
   * @return The map of all properties
   */
  @JsonIgnore
  @Nonnull
  public Map<String, Object> toMap()
  {
    final Map<String, Object> declaredFields = new LinkedHashMap<>(cloudSdkCustomFields);
    if( type != null ) declaredFields.put("type", type);
    return declaredFields;
  }

  /**
   * Set an unrecognizable property of this {@link OnYourDataAuthenticationOptions} instance. If the map previously contained a mapping
   * for the key, the old value is replaced by the specified value.
   * @param customFieldName The name of the property
   * @param customFieldValue The value of the property
   */
  @JsonIgnore
  public void setCustomField( @Nonnull String customFieldName, @Nullable Object customFieldValue )
  {
      cloudSdkCustomFields.put(customFieldName, customFieldValue);
  }


  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final OnYourDataAuthenticationOptions onYourDataAuthenticationOptions = (OnYourDataAuthenticationOptions) o;
    return Objects.equals(this.cloudSdkCustomFields, onYourDataAuthenticationOptions.cloudSdkCustomFields) &&
        Objects.equals(this.type, onYourDataAuthenticationOptions.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class OnYourDataAuthenticationOptions {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

