# assumptions:
#   - The current action runner has the SDK repo checked out (i.e. our custom stash and unstash actions are available)
#   - The current action runner has a JDK setup (i.e. `actions/setup-java` has been run)

name: "Unstash SDK targets"
description: "Unstashes the SDK target directories"

inputs:
  sdk-root:
    description: "The root directory of the SDK"
    required: false
    default: "."
  key:
    description: "The key to use when unstashing the SDK M2 directory"
    required: false
    default: "sdk-targets-${{ github.ref }}"

outputs:
  unstashed:
    description: "Whether the specified stash was unstashed"
    value: ${{ steps.unstash.outputs.cache-hit }}

runs:
  using: composite
  steps:
    - name: Print Action Start
      run: echo ">>>>> Starting Unstash SDK Targets Action; inputs = ${{ toJson(inputs) }}"
      shell: bash

    - name: Unstash
      id: unstash
      uses: ./.github/actions/unstash
      with:
        # NOTE: These paths must match the ones of the stash action EXACTLY
        path: ${{ inputs.sdk-root }}/**/target/*
        key: ${{ inputs.key }}

    - name: Print Action End
      if: always()
      run: echo "<<<<< Finished Unstash SDK Targets Action"
      shell: bash
