name: Bug Report
description: Released feature does not work as expected in the SAP Cloud SDK for Java.
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        This repository is for Java related issues only. Please open [JavaScript / TypeScript issues here](https://github.com/SAP/cloud-sdk-js/issues/new/choose)
  - type: textarea
    attributes:
      label: "Describe the Bug"
      description: "A clear and concise description of what the bug is."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Steps to Reproduce"
      description: "Steps to reproduce the behavior."
      placeholder: |
        1. Set up ...
        2. Execute ...
        3. Confirm ...
        4. See error
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Expected Behavior"
      description: "A clear and concise description of what you expected to happen. In case of HTTP requests, a working Postman (or similar) request is very helpful."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Screenshots"
      description: "Add screenshots to help explain your problem."
    validations:
      required: false
  - type: textarea
    attributes:
      label: "Used Versions"
      description: "Provide versions used in the project."
      value: |
        - Java and Maven version via `mvn --version`: ...
        - SAP Cloud SDK version: ...
        - Spring Boot or CAP version: ...
        - <details><summary>Dependency tree via `mvn dependency:tree`</summary>
            
            ```
            Dependency tree here
            ```
          </details>
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Code Examples"
      description: "Add code snippets as examples to help explain your problem. Please remove sensitive information."
      value: |
        ```java
        // Your code here
        ```
    validations:
      required: false
  - type: textarea
    attributes:
      label: "Stack Trace"
      description: "Add your stack trace here. Please remove sensitive information."
    validations:
      required: false
  - type: textarea
    attributes:
      label: "Log File"
      description: "Add your log file or related error message. Please remove sensitive information."
      value: |
        <details><summary>Log file</summary>
        ...
        </details>
    validations:
      required: false
  - type: dropdown
    attributes:
      label: "Affected Development Phase"
      description: "Choose the development phase affected by this issue."
      multiple: false
      options:
        - Getting Started
        - Development
        - Release
        - Production
    validations:
      required: true
  - type: dropdown
    attributes:
      label: "Impact"
      description: "Choose the impact severity."
      multiple: false
      options:
        - No Impact
        - Inconvenience
        - Impaired
        - Blocked
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Timeline"
      description: "Please briefly state your timeline, e.g., Go-Live in 12 weeks."
    validations:
      required: false
