name: Question
description: Ask a question about the SAP Cloud SDK for Java.
labels:
  - question
body:
  - type: markdown
    attributes:
      value: |
        This repository is for Java related issues only. Please open [JavaScript / TypeScript issues here](https://github.com/SAP/cloud-sdk-js/issues/new/choose)
  - type: textarea
    attributes:
      label: "Ask the Question"
      description: Give  a clear and concise description.
    validations:
      required: true
