name: "Scan With SpotBugs"
description: "Scans the SDK with SpotBugs"

inputs:
  maven-args:
    description: "The arguments to pass to Maven"
    required: false
    default: "--batch-mode --fail-at-end --show-version --threads 1C -DskipFormatting -Denforcer.skip -Djacoco.skip -Dmdep.analyze.skip"

runs:
  using: composite
  steps:
    - name: Print Action Start
      run: echo ">>>>> Starting Scan With SpotBugs Action; inputs = ${{ toJson(inputs) }}"
      shell: bash

    - name: Load Non-SDK M2
      uses: ./.github/actions/unstash-non-sdk-m2
    - name: Load SDK M2
      uses: ./.github/actions/unstash-sdk-m2
    - name: Load SDK Target Dirs
      uses: ./.github/actions/unstash-sdk-targets

    - name: Spotbugs
      run: |
        MVN_ARGS="${{ inputs.maven-args }} com.github.spotbugs:spotbugs-maven-plugin:spotbugs"
        echo "[DEBUG] Running Maven with arguments: $MVN_ARGS"
        mvn $MVN_ARGS
      shell: bash
    - name: Spotbugs Report
      run: python .pipeline/scripts/print-spotbugs.py
      shell: bash

    - name: Print Action End
      if: always()
      run: echo "<<<<< Finished Scan With SpotBugs Action"
      shell: bash
