name: Verify Local Changes
description: Verifies that there are no local changes in the current git repository

runs:
  using: composite
  steps:
    - name: Print Action Start
      run: echo ">>>>> Starting Verify Local Changes Action"
      shell: bash

    - name: Verify Local Changes
      run: |
        CHANGED_FILES="$(git --no-pager diff --name-only)"
        if [ ! -z "$CHANGED_FILES" ]; then
            echo "There are local changes in the following files:"
            echo "$CHANGED_FILES"
            echo "Printing the git diff:"
            git --no-pager diff
            exit 1
        fi
      shell: bash

    - name: Print Action End
      if: always()
      run: echo "<<<<< Finished Verify Local Changes Action"
      shell: bash
