/*
 * Copyright (c) 2024 SAP SE or an SAP affiliate company. All rights reserved.
 */

/*
 * AI Core
 * Provides tools to manage your scenarios and workflows in SAP AI Core. Execute pipelines as a batch job, for example to pre-process or train your models, or perform batch inference.  Serve inference requests of trained models. Deploy а trained machine learning model as a web service to serve inference requests with high performance.  Register your own Docker registry, synchronize your AI content from your own git repository, and register your own object store for training data and trained models. 
 *
 * The version of the OpenAPI document: 2.26.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.cloud.sdk.services.ai.model;

import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.sap.cloud.sdk.services.ai.model.ConfigurationId;
import com.sap.cloud.sdk.services.ai.model.ConfigurationName;
import com.sap.cloud.sdk.services.ai.model.DeploymentId;
import com.sap.cloud.sdk.services.ai.model.DeploymentStatus;
import com.sap.cloud.sdk.services.ai.model.DeploymentStatusMessage;
import com.sap.cloud.sdk.services.ai.model.ScenarioId;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * Detailed data about a deployment
 */

// CHECKSTYLE:OFF
public class DeploymentDetailData 
// CHECKSTYLE:ON
{
  @JsonProperty("id")
  private DeploymentId id;

  @JsonProperty("deploymentUrl")
  private String deploymentUrl;

  @JsonProperty("configurationId")
  private ConfigurationId configurationId;

  @JsonProperty("configurationName")
  private ConfigurationName configurationName;

  @JsonProperty("scenarioId")
  private ScenarioId scenarioId;

  @JsonProperty("status")
  private DeploymentStatus status;

  @JsonProperty("statusMessage")
  private DeploymentStatusMessage statusMessage;

  /**
   * Deployment target status
   */
  public enum TargetStatusEnum {
    /**
    * The RUNNING option of this DeploymentDetailData
    */
    RUNNING("RUNNING"),
    
    /**
    * The STOPPED option of this DeploymentDetailData
    */
    STOPPED("STOPPED"),
    
    /**
    * The DELETED option of this DeploymentDetailData
    */
    DELETED("DELETED");

    private String value;

    TargetStatusEnum(String value) {
      this.value = value;
    }

    /**
    * Get the value of the enum
    * @return The enum value
    */
    @JsonValue
    @Nonnull public String getValue() {
      return value;
    }

    /**
    * Get the String value of the enum value.
    * @return The enum value as String
    */
    @Override
    @Nonnull public String toString() {
      return String.valueOf(value);
    }

    /**
    * Get the enum value from a String value
    * @param value The String value
    * @return The enum value of type DeploymentDetailData
    */
    @JsonCreator
    @Nonnull public static TargetStatusEnum fromValue(@Nonnull final String value) {
      for (TargetStatusEnum b : TargetStatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  @JsonProperty("targetStatus")
  private TargetStatusEnum targetStatus;

  /**
   * Gets or Sets lastOperation
   */
  public enum LastOperationEnum {
    /**
    * The CREATE option of this DeploymentDetailData
    */
    CREATE("CREATE"),
    
    /**
    * The UPDATE option of this DeploymentDetailData
    */
    UPDATE("UPDATE"),
    
    /**
    * The DELETE option of this DeploymentDetailData
    */
    DELETE("DELETE"),
    
    /**
    * The CASCADE_UPDATE option of this DeploymentDetailData
    */
    CASCADE_UPDATE("CASCADE-UPDATE");

    private String value;

    LastOperationEnum(String value) {
      this.value = value;
    }

    /**
    * Get the value of the enum
    * @return The enum value
    */
    @JsonValue
    @Nonnull public String getValue() {
      return value;
    }

    /**
    * Get the String value of the enum value.
    * @return The enum value as String
    */
    @Override
    @Nonnull public String toString() {
      return String.valueOf(value);
    }

    /**
    * Get the enum value from a String value
    * @param value The String value
    * @return The enum value of type DeploymentDetailData
    */
    @JsonCreator
    @Nonnull public static LastOperationEnum fromValue(@Nonnull final String value) {
      for (LastOperationEnum b : LastOperationEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("lastOperation")
  private LastOperationEnum lastOperation;

  @JsonProperty("latestRunningConfigurationId")
  private ConfigurationId latestRunningConfigurationId;

  @JsonProperty("ttl")
  private String ttl;

  @JsonAnySetter
  @JsonAnyGetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

   /**
   * Set the id of this {@link DeploymentDetailData} instance and return the same instance.
   *
   * @param id  The id of this {@link DeploymentDetailData}
   * @return The same instance of this {@link DeploymentDetailData} class
   */
   @Nonnull public DeploymentDetailData id(@Nonnull final DeploymentId id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id  The id of this {@link DeploymentDetailData} instance.
  **/
  @Nonnull public DeploymentId getId() {
    return id;
  }

  /**
  * Set the id of this {@link DeploymentDetailData} instance.
  *
  * @param id  The id of this {@link DeploymentDetailData}
  */
  public void setId( @Nonnull final DeploymentId id) {
    this.id = id;
  }

   /**
   * Set the deploymentUrl of this {@link DeploymentDetailData} instance and return the same instance.
   *
   * @param deploymentUrl  Consumption URL of the deployment
   * @return The same instance of this {@link DeploymentDetailData} class
   */
   @Nonnull public DeploymentDetailData deploymentUrl(@Nonnull final String deploymentUrl) {
    this.deploymentUrl = deploymentUrl;
    return this;
  }

   /**
   * Consumption URL of the deployment
   * @return deploymentUrl  The deploymentUrl of this {@link DeploymentDetailData} instance.
  **/
  @Nonnull public String getDeploymentUrl() {
    return deploymentUrl;
  }

  /**
  * Set the deploymentUrl of this {@link DeploymentDetailData} instance.
  *
  * @param deploymentUrl  Consumption URL of the deployment
  */
  public void setDeploymentUrl( @Nonnull final String deploymentUrl) {
    this.deploymentUrl = deploymentUrl;
  }

   /**
   * Set the configurationId of this {@link DeploymentDetailData} instance and return the same instance.
   *
   * @param configurationId  The configurationId of this {@link DeploymentDetailData}
   * @return The same instance of this {@link DeploymentDetailData} class
   */
   @Nonnull public DeploymentDetailData configurationId(@Nonnull final ConfigurationId configurationId) {
    this.configurationId = configurationId;
    return this;
  }

   /**
   * Get configurationId
   * @return configurationId  The configurationId of this {@link DeploymentDetailData} instance.
  **/
  @Nonnull public ConfigurationId getConfigurationId() {
    return configurationId;
  }

  /**
  * Set the configurationId of this {@link DeploymentDetailData} instance.
  *
  * @param configurationId  The configurationId of this {@link DeploymentDetailData}
  */
  public void setConfigurationId( @Nonnull final ConfigurationId configurationId) {
    this.configurationId = configurationId;
  }

   /**
   * Set the configurationName of this {@link DeploymentDetailData} instance and return the same instance.
   *
   * @param configurationName  The configurationName of this {@link DeploymentDetailData}
   * @return The same instance of this {@link DeploymentDetailData} class
   */
   @Nonnull public DeploymentDetailData configurationName(@Nonnull final ConfigurationName configurationName) {
    this.configurationName = configurationName;
    return this;
  }

   /**
   * Get configurationName
   * @return configurationName  The configurationName of this {@link DeploymentDetailData} instance.
  **/
  @Nonnull public ConfigurationName getConfigurationName() {
    return configurationName;
  }

  /**
  * Set the configurationName of this {@link DeploymentDetailData} instance.
  *
  * @param configurationName  The configurationName of this {@link DeploymentDetailData}
  */
  public void setConfigurationName( @Nonnull final ConfigurationName configurationName) {
    this.configurationName = configurationName;
  }

   /**
   * Set the scenarioId of this {@link DeploymentDetailData} instance and return the same instance.
   *
   * @param scenarioId  The scenarioId of this {@link DeploymentDetailData}
   * @return The same instance of this {@link DeploymentDetailData} class
   */
   @Nonnull public DeploymentDetailData scenarioId(@Nonnull final ScenarioId scenarioId) {
    this.scenarioId = scenarioId;
    return this;
  }

   /**
   * Get scenarioId
   * @return scenarioId  The scenarioId of this {@link DeploymentDetailData} instance.
  **/
  @Nonnull public ScenarioId getScenarioId() {
    return scenarioId;
  }

  /**
  * Set the scenarioId of this {@link DeploymentDetailData} instance.
  *
  * @param scenarioId  The scenarioId of this {@link DeploymentDetailData}
  */
  public void setScenarioId( @Nonnull final ScenarioId scenarioId) {
    this.scenarioId = scenarioId;
  }

   /**
   * Set the status of this {@link DeploymentDetailData} instance and return the same instance.
   *
   * @param status  The status of this {@link DeploymentDetailData}
   * @return The same instance of this {@link DeploymentDetailData} class
   */
   @Nonnull public DeploymentDetailData status(@Nonnull final DeploymentStatus status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status  The status of this {@link DeploymentDetailData} instance.
  **/
  @Nonnull public DeploymentStatus getStatus() {
    return status;
  }

  /**
  * Set the status of this {@link DeploymentDetailData} instance.
  *
  * @param status  The status of this {@link DeploymentDetailData}
  */
  public void setStatus( @Nonnull final DeploymentStatus status) {
    this.status = status;
  }

   /**
   * Set the statusMessage of this {@link DeploymentDetailData} instance and return the same instance.
   *
   * @param statusMessage  The statusMessage of this {@link DeploymentDetailData}
   * @return The same instance of this {@link DeploymentDetailData} class
   */
   @Nonnull public DeploymentDetailData statusMessage(@Nonnull final DeploymentStatusMessage statusMessage) {
    this.statusMessage = statusMessage;
    return this;
  }

   /**
   * Get statusMessage
   * @return statusMessage  The statusMessage of this {@link DeploymentDetailData} instance.
  **/
  @Nonnull public DeploymentStatusMessage getStatusMessage() {
    return statusMessage;
  }

  /**
  * Set the statusMessage of this {@link DeploymentDetailData} instance.
  *
  * @param statusMessage  The statusMessage of this {@link DeploymentDetailData}
  */
  public void setStatusMessage( @Nonnull final DeploymentStatusMessage statusMessage) {
    this.statusMessage = statusMessage;
  }

   /**
   * Set the targetStatus of this {@link DeploymentDetailData} instance and return the same instance.
   *
   * @param targetStatus  Deployment target status
   * @return The same instance of this {@link DeploymentDetailData} class
   */
   @Nonnull public DeploymentDetailData targetStatus(@Nonnull final TargetStatusEnum targetStatus) {
    this.targetStatus = targetStatus;
    return this;
  }

   /**
   * Deployment target status
   * @return targetStatus  The targetStatus of this {@link DeploymentDetailData} instance.
  **/
  @Nonnull public TargetStatusEnum getTargetStatus() {
    return targetStatus;
  }

  /**
  * Set the targetStatus of this {@link DeploymentDetailData} instance.
  *
  * @param targetStatus  Deployment target status
  */
  public void setTargetStatus( @Nonnull final TargetStatusEnum targetStatus) {
    this.targetStatus = targetStatus;
  }

   /**
   * Set the lastOperation of this {@link DeploymentDetailData} instance and return the same instance.
   *
   * @param lastOperation  The lastOperation of this {@link DeploymentDetailData}
   * @return The same instance of this {@link DeploymentDetailData} class
   */
   @Nonnull public DeploymentDetailData lastOperation(@Nonnull final LastOperationEnum lastOperation) {
    this.lastOperation = lastOperation;
    return this;
  }

   /**
   * Get lastOperation
   * @return lastOperation  The lastOperation of this {@link DeploymentDetailData} instance.
  **/
  @Nonnull public LastOperationEnum getLastOperation() {
    return lastOperation;
  }

  /**
  * Set the lastOperation of this {@link DeploymentDetailData} instance.
  *
  * @param lastOperation  The lastOperation of this {@link DeploymentDetailData}
  */
  public void setLastOperation( @Nonnull final LastOperationEnum lastOperation) {
    this.lastOperation = lastOperation;
  }

   /**
   * Set the latestRunningConfigurationId of this {@link DeploymentDetailData} instance and return the same instance.
   *
   * @param latestRunningConfigurationId  The latestRunningConfigurationId of this {@link DeploymentDetailData}
   * @return The same instance of this {@link DeploymentDetailData} class
   */
   @Nonnull public DeploymentDetailData latestRunningConfigurationId(@Nonnull final ConfigurationId latestRunningConfigurationId) {
    this.latestRunningConfigurationId = latestRunningConfigurationId;
    return this;
  }

   /**
   * Get latestRunningConfigurationId
   * @return latestRunningConfigurationId  The latestRunningConfigurationId of this {@link DeploymentDetailData} instance.
  **/
  @Nonnull public ConfigurationId getLatestRunningConfigurationId() {
    return latestRunningConfigurationId;
  }

  /**
  * Set the latestRunningConfigurationId of this {@link DeploymentDetailData} instance.
  *
  * @param latestRunningConfigurationId  The latestRunningConfigurationId of this {@link DeploymentDetailData}
  */
  public void setLatestRunningConfigurationId( @Nonnull final ConfigurationId latestRunningConfigurationId) {
    this.latestRunningConfigurationId = latestRunningConfigurationId;
  }

   /**
   * Set the ttl of this {@link DeploymentDetailData} instance and return the same instance.
   *
   * @param ttl  Time to live for a deployment. Its value can be either null or a number followed by the unit (any of following values, minutes(m|M), hours(h|H) or days(d|D))
   * @return The same instance of this {@link DeploymentDetailData} class
   */
   @Nonnull public DeploymentDetailData ttl(@Nonnull final String ttl) {
    this.ttl = ttl;
    return this;
  }

   /**
   * Time to live for a deployment. Its value can be either null or a number followed by the unit (any of following values, minutes(m|M), hours(h|H) or days(d|D))
   * @return ttl  The ttl of this {@link DeploymentDetailData} instance.
  **/
  @Nonnull public String getTtl() {
    return ttl;
  }

  /**
  * Set the ttl of this {@link DeploymentDetailData} instance.
  *
  * @param ttl  Time to live for a deployment. Its value can be either null or a number followed by the unit (any of following values, minutes(m|M), hours(h|H) or days(d|D))
  */
  public void setTtl( @Nonnull final String ttl) {
    this.ttl = ttl;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link DeploymentDetailData}.
   * @return The set of properties names
   */
  @JsonIgnore
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of this {@link DeploymentDetailData} instance.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  public Object getCustomField(@Nonnull final String name) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("DeploymentDetailData has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  /**
   * Set an unrecognizable property of this {@link DeploymentDetailData} instance. If the map previously contained a mapping
   * for the key, the old value is replaced by the specified value.
   * @param customFieldName The name of the property
   * @param customFieldValue The value of the property
   */
  @JsonIgnore
  public void setCustomField( @Nonnull String customFieldName, @Nullable Object customFieldValue )
  {
      cloudSdkCustomFields.put(customFieldName, customFieldValue);
  }


  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final DeploymentDetailData deploymentDetailData = (DeploymentDetailData) o;
    return Objects.equals(this.cloudSdkCustomFields, deploymentDetailData.cloudSdkCustomFields) &&
        Objects.equals(this.id, deploymentDetailData.id) &&
        Objects.equals(this.deploymentUrl, deploymentDetailData.deploymentUrl) &&
        Objects.equals(this.configurationId, deploymentDetailData.configurationId) &&
        Objects.equals(this.configurationName, deploymentDetailData.configurationName) &&
        Objects.equals(this.scenarioId, deploymentDetailData.scenarioId) &&
        Objects.equals(this.status, deploymentDetailData.status) &&
        Objects.equals(this.statusMessage, deploymentDetailData.statusMessage) &&
        Objects.equals(this.targetStatus, deploymentDetailData.targetStatus) &&
        Objects.equals(this.lastOperation, deploymentDetailData.lastOperation) &&
        Objects.equals(this.latestRunningConfigurationId, deploymentDetailData.latestRunningConfigurationId) &&
        Objects.equals(this.ttl, deploymentDetailData.ttl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, deploymentUrl, configurationId, configurationName, scenarioId, status, statusMessage, targetStatus, lastOperation, latestRunningConfigurationId, ttl, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class DeploymentDetailData {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    deploymentUrl: ").append(toIndentedString(deploymentUrl)).append("\n");
    sb.append("    configurationId: ").append(toIndentedString(configurationId)).append("\n");
    sb.append("    configurationName: ").append(toIndentedString(configurationName)).append("\n");
    sb.append("    scenarioId: ").append(toIndentedString(scenarioId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    statusMessage: ").append(toIndentedString(statusMessage)).append("\n");
    sb.append("    targetStatus: ").append(toIndentedString(targetStatus)).append("\n");
    sb.append("    lastOperation: ").append(toIndentedString(lastOperation)).append("\n");
    sb.append("    latestRunningConfigurationId: ").append(toIndentedString(latestRunningConfigurationId)).append("\n");
    sb.append("    ttl: ").append(toIndentedString(ttl)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

