/*
 * Copyright (c) 2024 SAP SE or an SAP affiliate company. All rights reserved.
 */

/*
 * AI Core
 * Provides tools to manage your scenarios and workflows in SAP AI Core. Execute pipelines as a batch job, for example to pre-process or train your models, or perform batch inference.  Serve inference requests of trained models. Deploy а trained machine learning model as a web service to serve inference requests with high performance.  Register your own Docker registry, synchronize your AI content from your own git repository, and register your own object store for training data and trained models. 
 *
 * The version of the OpenAPI document: 2.26.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.cloud.sdk.services.ai.model;

import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.sap.cloud.sdk.services.ai.model.ServiceServicePlanItemMetadata;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * ServiceServicePlanItem
 */

// CHECKSTYLE:OFF
public class ServiceServicePlanItem 
// CHECKSTYLE:ON
{
  @JsonProperty("description")
  private String description;

  @JsonProperty("free")
  private Boolean free;

  @JsonProperty("id")
  private String id;

  @JsonProperty("name")
  private String name;

  @JsonProperty("metadata")
  private ServiceServicePlanItemMetadata metadata;

  @JsonAnySetter
  @JsonAnyGetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

   /**
   * Set the description of this {@link ServiceServicePlanItem} instance and return the same instance.
   *
   * @param description  description of the service plan
   * @return The same instance of this {@link ServiceServicePlanItem} class
   */
   @Nonnull public ServiceServicePlanItem description(@Nonnull final String description) {
    this.description = description;
    return this;
  }

   /**
   * description of the service plan
   * @return description  The description of this {@link ServiceServicePlanItem} instance.
  **/
  @Nonnull public String getDescription() {
    return description;
  }

  /**
  * Set the description of this {@link ServiceServicePlanItem} instance.
  *
  * @param description  description of the service plan
  */
  public void setDescription( @Nonnull final String description) {
    this.description = description;
  }

   /**
   * Set the free of this {@link ServiceServicePlanItem} instance and return the same instance.
   *
   * @param free  if the service plan free
   * @return The same instance of this {@link ServiceServicePlanItem} class
   */
   @Nonnull public ServiceServicePlanItem free(@Nonnull final Boolean free) {
    this.free = free;
    return this;
  }

   /**
   * if the service plan free
   * @return free  The free of this {@link ServiceServicePlanItem} instance.
  **/
  @Nonnull public Boolean isFree() {
    return free;
  }

  /**
  * Set the free of this {@link ServiceServicePlanItem} instance.
  *
  * @param free  if the service plan free
  */
  public void setFree( @Nonnull final Boolean free) {
    this.free = free;
  }

   /**
   * Set the id of this {@link ServiceServicePlanItem} instance and return the same instance.
   *
   * @param id  id of the service plan
   * @return The same instance of this {@link ServiceServicePlanItem} class
   */
   @Nonnull public ServiceServicePlanItem id(@Nonnull final String id) {
    this.id = id;
    return this;
  }

   /**
   * id of the service plan
   * @return id  The id of this {@link ServiceServicePlanItem} instance.
  **/
  @Nonnull public String getId() {
    return id;
  }

  /**
  * Set the id of this {@link ServiceServicePlanItem} instance.
  *
  * @param id  id of the service plan
  */
  public void setId( @Nonnull final String id) {
    this.id = id;
  }

   /**
   * Set the name of this {@link ServiceServicePlanItem} instance and return the same instance.
   *
   * @param name  name of the service plan
   * @return The same instance of this {@link ServiceServicePlanItem} class
   */
   @Nonnull public ServiceServicePlanItem name(@Nonnull final String name) {
    this.name = name;
    return this;
  }

   /**
   * name of the service plan
   * @return name  The name of this {@link ServiceServicePlanItem} instance.
  **/
  @Nonnull public String getName() {
    return name;
  }

  /**
  * Set the name of this {@link ServiceServicePlanItem} instance.
  *
  * @param name  name of the service plan
  */
  public void setName( @Nonnull final String name) {
    this.name = name;
  }

   /**
   * Set the metadata of this {@link ServiceServicePlanItem} instance and return the same instance.
   *
   * @param metadata  The metadata of this {@link ServiceServicePlanItem}
   * @return The same instance of this {@link ServiceServicePlanItem} class
   */
   @Nonnull public ServiceServicePlanItem metadata(@Nonnull final ServiceServicePlanItemMetadata metadata) {
    this.metadata = metadata;
    return this;
  }

   /**
   * Get metadata
   * @return metadata  The metadata of this {@link ServiceServicePlanItem} instance.
  **/
  @Nonnull public ServiceServicePlanItemMetadata getMetadata() {
    return metadata;
  }

  /**
  * Set the metadata of this {@link ServiceServicePlanItem} instance.
  *
  * @param metadata  The metadata of this {@link ServiceServicePlanItem}
  */
  public void setMetadata( @Nonnull final ServiceServicePlanItemMetadata metadata) {
    this.metadata = metadata;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link ServiceServicePlanItem}.
   * @return The set of properties names
   */
  @JsonIgnore
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of this {@link ServiceServicePlanItem} instance.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  public Object getCustomField(@Nonnull final String name) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("ServiceServicePlanItem has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  /**
   * Set an unrecognizable property of this {@link ServiceServicePlanItem} instance. If the map previously contained a mapping
   * for the key, the old value is replaced by the specified value.
   * @param customFieldName The name of the property
   * @param customFieldValue The value of the property
   */
  @JsonIgnore
  public void setCustomField( @Nonnull String customFieldName, @Nullable Object customFieldValue )
  {
      cloudSdkCustomFields.put(customFieldName, customFieldValue);
  }


  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final ServiceServicePlanItem serviceServicePlanItem = (ServiceServicePlanItem) o;
    return Objects.equals(this.cloudSdkCustomFields, serviceServicePlanItem.cloudSdkCustomFields) &&
        Objects.equals(this.description, serviceServicePlanItem.description) &&
        Objects.equals(this.free, serviceServicePlanItem.free) &&
        Objects.equals(this.id, serviceServicePlanItem.id) &&
        Objects.equals(this.name, serviceServicePlanItem.name) &&
        Objects.equals(this.metadata, serviceServicePlanItem.metadata);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, free, id, name, metadata, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class ServiceServicePlanItem {\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    free: ").append(toIndentedString(free)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

