/*
 * Copyright (c) 2024 SAP SE or an SAP affiliate company. All rights reserved.
 */

/*
 * AI Core
 * Provides tools to manage your scenarios and workflows in SAP AI Core. Execute pipelines as a batch job, for example to pre-process or train your models, or perform batch inference.  Serve inference requests of trained models. Deploy а trained machine learning model as a web service to serve inference requests with high performance.  Register your own Docker registry, synchronize your AI content from your own git repository, and register your own object store for training data and trained models. 
 *
 * The version of the OpenAPI document: 2.26.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.cloud.sdk.services.ai.model;

import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.sap.cloud.sdk.services.ai.model.ScenarioId;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * VersionDetailData
 */

// CHECKSTYLE:OFF
public class VersionDetailData 
// CHECKSTYLE:ON
{
  @JsonProperty("id")
  private String id;

  @JsonProperty("scenarioId")
  private ScenarioId scenarioId;

  @JsonAnySetter
  @JsonAnyGetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

   /**
   * Set the id of this {@link VersionDetailData} instance and return the same instance.
   *
   * @param id  Version ID
   * @return The same instance of this {@link VersionDetailData} class
   */
   @Nonnull public VersionDetailData id(@Nonnull final String id) {
    this.id = id;
    return this;
  }

   /**
   * Version ID
   * @return id  The id of this {@link VersionDetailData} instance.
  **/
  @Nonnull public String getId() {
    return id;
  }

  /**
  * Set the id of this {@link VersionDetailData} instance.
  *
  * @param id  Version ID
  */
  public void setId( @Nonnull final String id) {
    this.id = id;
  }

   /**
   * Set the scenarioId of this {@link VersionDetailData} instance and return the same instance.
   *
   * @param scenarioId  The scenarioId of this {@link VersionDetailData}
   * @return The same instance of this {@link VersionDetailData} class
   */
   @Nonnull public VersionDetailData scenarioId(@Nonnull final ScenarioId scenarioId) {
    this.scenarioId = scenarioId;
    return this;
  }

   /**
   * Get scenarioId
   * @return scenarioId  The scenarioId of this {@link VersionDetailData} instance.
  **/
  @Nonnull public ScenarioId getScenarioId() {
    return scenarioId;
  }

  /**
  * Set the scenarioId of this {@link VersionDetailData} instance.
  *
  * @param scenarioId  The scenarioId of this {@link VersionDetailData}
  */
  public void setScenarioId( @Nonnull final ScenarioId scenarioId) {
    this.scenarioId = scenarioId;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link VersionDetailData}.
   * @return The set of properties names
   */
  @JsonIgnore
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of this {@link VersionDetailData} instance.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  public Object getCustomField(@Nonnull final String name) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("VersionDetailData has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  /**
   * Set an unrecognizable property of this {@link VersionDetailData} instance. If the map previously contained a mapping
   * for the key, the old value is replaced by the specified value.
   * @param customFieldName The name of the property
   * @param customFieldValue The value of the property
   */
  @JsonIgnore
  public void setCustomField( @Nonnull String customFieldName, @Nullable Object customFieldValue )
  {
      cloudSdkCustomFields.put(customFieldName, customFieldValue);
  }


  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final VersionDetailData versionDetailData = (VersionDetailData) o;
    return Objects.equals(this.cloudSdkCustomFields, versionDetailData.cloudSdkCustomFields) &&
        Objects.equals(this.id, versionDetailData.id) &&
        Objects.equals(this.scenarioId, versionDetailData.scenarioId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, scenarioId, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class VersionDetailData {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    scenarioId: ").append(toIndentedString(scenarioId)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

