name: Unstash
description: Unstashes the specified directories. This action uses the GitHub Cache API internally.

inputs:
  path:
    description: "The path(s) (supports GLOB pattern) to stash"
    required: true
  key:
    description: "The stash key to use"
    required: true

outputs:
  unstashed:
    description: "Whether the specified stash was unstashed"
    value: ${{ steps.unstash.outputs.cache-hit }}

runs:
  using: composite
  steps:
    - name: Print Action Start
      run: echo ">>>>> Starting Unstash Action; inputs = ${{ toJson(inputs) }}"
      shell: bash

    - name: Unstash
      id: unstash
      uses: actions/cache/restore@v3
      with:
        path: ${{ inputs.path }}
        key: ${{ inputs.key }}

    - name: Print Action End
      if: always()
      run: echo "<<<<< Finished Unstash Action"
      shell: bash
