/*
 * Copyright (c) 2026 SAP SE or an SAP affiliate company. All rights reserved.
 */

/*
 * String and File multipart body
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.cloud.sdk.datamodel.rest.test.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * PredictionConfig
 */
// CHECKSTYLE:OFF
public class PredictionConfig 
// CHECKSTYLE:ON
{
  @JsonProperty("test")
  private String test;

  @JsonAnySetter
  @JsonAnyGetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

  /**
   * Set the test of this {@link PredictionConfig} instance and return the same instance.
   *
   * @param test  The test of this {@link PredictionConfig}
   * @return The same instance of this {@link PredictionConfig} class
   */
  @Nonnull public PredictionConfig test( @Nullable final String test) {
    this.test = test;
    return this;
  }

  /**
   * Get test
   * @return test  The test of this {@link PredictionConfig} instance.
   */
  @Nonnull
  public String getTest() {
    return test;
  }

  /**
   * Set the test of this {@link PredictionConfig} instance.
   *
   * @param test  The test of this {@link PredictionConfig}
   */
  public void setTest( @Nullable final String test) {
    this.test = test;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link PredictionConfig}.
   * @return The set of properties names
   */
  @JsonIgnore
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of this {@link PredictionConfig} instance.
   * @deprecated Use {@link #toMap()} instead.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  @Deprecated
  public Object getCustomField( @Nonnull final String name ) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("PredictionConfig has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  /**
   * Get the value of all properties of this {@link PredictionConfig} instance including unrecognized properties.
   *
   * @return The map of all properties
   */
  @JsonIgnore
  @Nonnull
  public Map<String, Object> toMap()
  {
    final Map<String, Object> declaredFields = new LinkedHashMap<>(cloudSdkCustomFields);
    if( test != null ) declaredFields.put("test", test);
    return declaredFields;
  }

  /**
   * Set an unrecognizable property of this {@link PredictionConfig} instance. If the map previously contained a mapping
   * for the key, the old value is replaced by the specified value.
   * @param customFieldName The name of the property
   * @param customFieldValue The value of the property
   */
  @JsonIgnore
  public void setCustomField( @Nonnull String customFieldName, @Nullable Object customFieldValue )
  {
      cloudSdkCustomFields.put(customFieldName, customFieldValue);
  }


  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final PredictionConfig predictionConfig = (PredictionConfig) o;
    return Objects.equals(this.cloudSdkCustomFields, predictionConfig.cloudSdkCustomFields) &&
        Objects.equals(this.test, predictionConfig.test);
  }

  @Override
  public int hashCode() {
    return Objects.hash(test, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class PredictionConfig {\n");
    sb.append("    test: ").append(toIndentedString(test)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

