name: "Scan With CheckStyle"
description: "Scans the SDK with CheckStyle"

inputs:
  maven-args:
    description: "The arguments to pass to Maven"
    required: false
    default: "--batch-mode --fail-at-end --show-version --threads 1C -DskipFormatting -Denforcer.skip -Djacoco.skip -Dmdep.analyze.skip"

runs:
  using: composite
  steps:
    - name: Print Action Start
      run: echo ">>>>> Starting Scan With CheckStyle Action; inputs = ${{ toJson(inputs) }}"
      shell: bash

    - name: Load Non-SDK M2
      uses: ./.github/actions/unstash-non-sdk-m2
    - name: Load SDK M2
      uses: ./.github/actions/unstash-sdk-m2
    - name: Load SDK Target Dirs
      uses: ./.github/actions/unstash-sdk-targets

    - name: Checkstyle
      run: |
        MVN_ARGS="${{ inputs.maven-args }} -P!build-test-modules org.apache.maven.plugins:maven-checkstyle-plugin:checkstyle"
        echo "[DEBUG] Running Maven with arguments: $MVN_ARGS"
        mvn $MVN_ARGS
      shell: bash
    - name: Checkstyle Results
      run: python .pipeline/scripts/print-checkstyle.py
      shell: bash

    - name: Print Action End
      if: always()
      run: echo "<<<<< Finished Scan With CheckStyle Action"
      shell: bash
