/*
 * Copyright (c) 2026 SAP SE or an SAP affiliate company. All rights reserved.
 */

/*
 * SodaStore API
 * API for managing soda products and orders in SodaStore.
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.cloud.sdk.datamodel.openapi.apache.sample.model;

import java.util.List;

import javax.annotation.Nonnull;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * FantaFlavor
 */
public interface FantaFlavor
{
    /**
     * Helper class to create {@code String } that implements {@link FantaFlavor}.
     */
    record InnerString(@com.fasterxml.jackson.annotation.JsonValue @Nonnull String value) implements FantaFlavor {}

    /**
     * Creator to enable deserialization of {@code String }.
     *
     * @param val
     *            the value to use
     * @return a new instance of {@link InnerString}.
     */
    @com.fasterxml.jackson.annotation.JsonCreator
    @Nonnull
    static InnerString create( @Nonnull final String val )
    {
        return new InnerString(val);
    }

    /**
     * Helper class to create {@code Integer } that implements {@link FantaFlavor}.
     */
    record InnerInteger(@com.fasterxml.jackson.annotation.JsonValue @Nonnull Integer value) implements FantaFlavor {}

    /**
     * Creator to enable deserialization of {@code Integer }.
     *
     * @param val
     *            the value to use
     * @return a new instance of {@link InnerInteger}.
     */
    @com.fasterxml.jackson.annotation.JsonCreator
    @Nonnull
    static InnerInteger create( @Nonnull final Integer val )
    {
        return new InnerInteger(val);
    }

    /**
     * Helper class to create {@code FlavorType } that implements {@link FantaFlavor}.
     */
    record InnerFlavorType(@com.fasterxml.jackson.annotation.JsonValue @Nonnull FlavorType value) implements FantaFlavor {}

    /**
     * Creator to enable deserialization of {@code FlavorType }.
     *
     * @param val
     *            the value to use
     * @return a new instance of {@link InnerFlavorType}.
     */
    @com.fasterxml.jackson.annotation.JsonCreator
    @Nonnull
    static InnerFlavorType createInnerFlavorType( @Nonnull final FlavorType val )
    {
        return new InnerFlavorType(val);
    }

    /**
     * Helper class to create {@code List<FlavorType> } that implements {@link FantaFlavor}.
     */
    record ListOfFlavorTypes(@com.fasterxml.jackson.annotation.JsonValue @Nonnull List<FlavorType> values) implements FantaFlavor {}

    /**
     * Creator to enable deserialization of {@code List<FlavorType> }.
     *
     * @param val
     *            the value to use
     * @return a new instance of {@link ListOfFlavorTypes}.
     */
    @com.fasterxml.jackson.annotation.JsonCreator
    @Nonnull
    static ListOfFlavorTypes createListOfFlavorTypes( @Nonnull final List<FlavorType> val )
    {
        return new ListOfFlavorTypes(val);
    }

}
