/*
 * Copyright (c) 2025 SAP SE or an SAP affiliate company. All rights reserved.
 */

/*
 * Prompt Registry API
 * Prompt Storage service for Design time & Runtime prompt templates.
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.cloud.sdk.datamodel.openapi.apache.sample.model;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.annotations.Beta;

/**
 * MaskingModuleConfigMaskingProviders
 */

@Beta // CHECKSTYLE:OFF
public class MaskingModuleConfigMaskingProviders implements MaskingModuleConfig
// CHECKSTYLE:ON
{
    @JsonProperty( "masking_providers" )
    private List<DPIConfig> maskingProviders = new ArrayList<>();

    @JsonAnySetter
    @JsonAnyGetter
    private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

    /**
     * Default constructor for MaskingModuleConfigMaskingProviders.
     */
    protected MaskingModuleConfigMaskingProviders()
    {
    }

    /**
     * Set the maskingProviders of this {@link MaskingModuleConfigMaskingProviders} instance and return the same
     * instance.
     *
     * @param maskingProviders
     *            List of masking service providers. **DEPRECATED**: will be removed Sept 15, 2026. Use
     *            &#x60;providers&#x60; property instead.
     * @return The same instance of this {@link MaskingModuleConfigMaskingProviders} class
     */
    @Nonnull
    public MaskingModuleConfigMaskingProviders maskingProviders( @Nonnull final List<DPIConfig> maskingProviders )
    {
        this.maskingProviders = maskingProviders;
        return this;
    }

    /**
     * Add one maskingProviders instance to this {@link MaskingModuleConfigMaskingProviders}.
     *
     * @param maskingProvidersItem
     *            The maskingProviders that should be added
     * @return The same instance of type {@link MaskingModuleConfigMaskingProviders}
     */
    @Nonnull
    public MaskingModuleConfigMaskingProviders addMaskingProvidersItem( @Nonnull final DPIConfig maskingProvidersItem )
    {
        if( this.maskingProviders == null ) {
            this.maskingProviders = new ArrayList<>();
        }
        this.maskingProviders.add(maskingProvidersItem);
        return this;
    }

    /**
     * List of masking service providers. **DEPRECATED**: will be removed Sept 15, 2026. Use &#x60;providers&#x60;
     * property instead.
     *
     * @return maskingProviders The maskingProviders of this {@link MaskingModuleConfigMaskingProviders} instance.
     * @deprecated
     */
    @Deprecated
    @Nonnull
    public List<DPIConfig> getMaskingProviders()
    {
        return maskingProviders;
    }

    /**
     * Set the maskingProviders of this {@link MaskingModuleConfigMaskingProviders} instance.
     *
     * @param maskingProviders
     *            List of masking service providers. **DEPRECATED**: will be removed Sept 15, 2026. Use
     *            &#x60;providers&#x60; property instead.
     */
    public void setMaskingProviders( @Nonnull final List<DPIConfig> maskingProviders )
    {
        this.maskingProviders = maskingProviders;
    }

    /**
     * Get the names of the unrecognizable properties of the {@link MaskingModuleConfigMaskingProviders}.
     *
     * @return The set of properties names
     */
    @JsonIgnore
    @Nonnull
    public Set<String> getCustomFieldNames()
    {
        return cloudSdkCustomFields.keySet();
    }

    /**
     * Get the value of an unrecognizable property of this {@link MaskingModuleConfigMaskingProviders} instance.
     *
     * @deprecated Use {@link #toMap()} instead.
     * @param name
     *            The name of the property
     * @return The value of the property
     * @throws NoSuchElementException
     *             If no property with the given name could be found.
     */
    @Nullable
    @Deprecated
    public Object getCustomField( @Nonnull final String name )
        throws NoSuchElementException
    {
        if( !cloudSdkCustomFields.containsKey(name) ) {
            throw new NoSuchElementException(
                "MaskingModuleConfigMaskingProviders has no field with name '" + name + "'.");
        }
        return cloudSdkCustomFields.get(name);
    }

    /**
     * Get the value of all properties of this {@link MaskingModuleConfigMaskingProviders} instance including
     * unrecognized properties.
     *
     * @return The map of all properties
     */
    @JsonIgnore
    @Nonnull
    public Map<String, Object> toMap()
    {
        final Map<String, Object> declaredFields = new LinkedHashMap<>(cloudSdkCustomFields);
        if( maskingProviders != null )
            declaredFields.put("maskingProviders", maskingProviders);
        return declaredFields;
    }

    /**
     * Set an unrecognizable property of this {@link MaskingModuleConfigMaskingProviders} instance. If the map
     * previously contained a mapping for the key, the old value is replaced by the specified value.
     *
     * @param customFieldName
     *            The name of the property
     * @param customFieldValue
     *            The value of the property
     */
    @JsonIgnore
    public void setCustomField( @Nonnull String customFieldName, @Nullable Object customFieldValue )
    {
        cloudSdkCustomFields.put(customFieldName, customFieldValue);
    }

    @Override
    public boolean equals( @Nullable final java.lang.Object o )
    {
        if( this == o ) {
            return true;
        }
        if( o == null || getClass() != o.getClass() ) {
            return false;
        }
        final MaskingModuleConfigMaskingProviders maskingModuleConfigMaskingProviders =
            (MaskingModuleConfigMaskingProviders) o;
        return Objects.equals(this.cloudSdkCustomFields, maskingModuleConfigMaskingProviders.cloudSdkCustomFields)
            && Objects.equals(this.maskingProviders, maskingModuleConfigMaskingProviders.maskingProviders);
    }

    @Override
    public int hashCode()
    {
        return Objects.hash(maskingProviders, cloudSdkCustomFields);
    }

    @Override
    @Nonnull
    public String toString()
    {
        final StringBuilder sb = new StringBuilder();
        sb.append("class MaskingModuleConfigMaskingProviders {\n");
        sb.append("    maskingProviders: ").append(toIndentedString(maskingProviders)).append("\n");
        cloudSdkCustomFields
            .forEach(( k, v ) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first line).
     */
    private String toIndentedString( final java.lang.Object o )
    {
        if( o == null ) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
