/*
 * Copyright (c) 2025 SAP SE or an SAP affiliate company. All rights reserved.
 */

/*
 * Prompt Registry API
 * Prompt Storage service for Design time & Runtime prompt templates.
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.cloud.sdk.datamodel.openapi.apache.sample.model;

import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import com.google.common.annotations.Beta;

/**
 * MessageToolCall
 */

@Beta // CHECKSTYLE:OFF
public class MessageToolCall
// CHECKSTYLE:ON
{
    @JsonProperty( "id" )
    private String id;

    /**
     * The type of the tool. Currently, only &#x60;function&#x60; is supported.
     */
    public enum TypeEnum
    {
        /**
         * The FUNCTION option of this MessageToolCall
         */
        FUNCTION("function"),

        /**
         * The UNKNOWN_DEFAULT_OPEN_API option of this MessageToolCall
         */
        UNKNOWN_DEFAULT_OPEN_API("unknown_default_open_api");

        private String value;

        TypeEnum( String value )
        {
            this.value = value;
        }

        /**
         * Get the value of the enum
         *
         * @return The enum value
         */
        @JsonValue
        @Nonnull
        public String getValue()
        {
            return value;
        }

        /**
         * Get the String value of the enum value.
         *
         * @return The enum value as String
         */
        @Override
        @Nonnull
        public String toString()
        {
            return String.valueOf(value);
        }

        /**
         * Get the enum value from a String value
         *
         * @param value
         *            The String value
         * @return The enum value of type MessageToolCall
         */
        @JsonCreator
        @Nonnull
        public static TypeEnum fromValue( @Nonnull final String value )
        {
            for( TypeEnum b : TypeEnum.values() ) {
                if( b.value.equals(value) ) {
                    return b;
                }
            }
            return UNKNOWN_DEFAULT_OPEN_API;
        }
    }

    @JsonProperty( "type" )
    private TypeEnum type;

    @JsonProperty( "function" )
    private MessageToolCallFunction function;

    @JsonAnySetter
    @JsonAnyGetter
    private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

    /**
     * Default constructor for MessageToolCall.
     */
    protected MessageToolCall()
    {
    }

    /**
     * Set the id of this {@link MessageToolCall} instance and return the same instance.
     *
     * @param id
     *            The ID of the tool call.
     * @return The same instance of this {@link MessageToolCall} class
     */
    @Nonnull
    public MessageToolCall id( @Nonnull final String id )
    {
        this.id = id;
        return this;
    }

    /**
     * The ID of the tool call.
     *
     * @return id The id of this {@link MessageToolCall} instance.
     */
    @Nonnull
    public String getId()
    {
        return id;
    }

    /**
     * Set the id of this {@link MessageToolCall} instance.
     *
     * @param id
     *            The ID of the tool call.
     */
    public void setId( @Nonnull final String id )
    {
        this.id = id;
    }

    /**
     * Set the type of this {@link MessageToolCall} instance and return the same instance.
     *
     * @param type
     *            The type of the tool. Currently, only &#x60;function&#x60; is supported.
     * @return The same instance of this {@link MessageToolCall} class
     */
    @Nonnull
    public MessageToolCall type( @Nonnull final TypeEnum type )
    {
        this.type = type;
        return this;
    }

    /**
     * The type of the tool. Currently, only &#x60;function&#x60; is supported.
     *
     * @return type The type of this {@link MessageToolCall} instance.
     */
    @Nonnull
    public TypeEnum getType()
    {
        return type;
    }

    /**
     * Set the type of this {@link MessageToolCall} instance.
     *
     * @param type
     *            The type of the tool. Currently, only &#x60;function&#x60; is supported.
     */
    public void setType( @Nonnull final TypeEnum type )
    {
        this.type = type;
    }

    /**
     * Set the function of this {@link MessageToolCall} instance and return the same instance.
     *
     * @param function
     *            The function of this {@link MessageToolCall}
     * @return The same instance of this {@link MessageToolCall} class
     */
    @Nonnull
    public MessageToolCall function( @Nonnull final MessageToolCallFunction function )
    {
        this.function = function;
        return this;
    }

    /**
     * Get function
     *
     * @return function The function of this {@link MessageToolCall} instance.
     */
    @Nonnull
    public MessageToolCallFunction getFunction()
    {
        return function;
    }

    /**
     * Set the function of this {@link MessageToolCall} instance.
     *
     * @param function
     *            The function of this {@link MessageToolCall}
     */
    public void setFunction( @Nonnull final MessageToolCallFunction function )
    {
        this.function = function;
    }

    /**
     * Get the names of the unrecognizable properties of the {@link MessageToolCall}.
     *
     * @return The set of properties names
     */
    @JsonIgnore
    @Nonnull
    public Set<String> getCustomFieldNames()
    {
        return cloudSdkCustomFields.keySet();
    }

    /**
     * Get the value of an unrecognizable property of this {@link MessageToolCall} instance.
     *
     * @deprecated Use {@link #toMap()} instead.
     * @param name
     *            The name of the property
     * @return The value of the property
     * @throws NoSuchElementException
     *             If no property with the given name could be found.
     */
    @Nullable
    @Deprecated
    public Object getCustomField( @Nonnull final String name )
        throws NoSuchElementException
    {
        if( !cloudSdkCustomFields.containsKey(name) ) {
            throw new NoSuchElementException("MessageToolCall has no field with name '" + name + "'.");
        }
        return cloudSdkCustomFields.get(name);
    }

    /**
     * Get the value of all properties of this {@link MessageToolCall} instance including unrecognized properties.
     *
     * @return The map of all properties
     */
    @JsonIgnore
    @Nonnull
    public Map<String, Object> toMap()
    {
        final Map<String, Object> declaredFields = new LinkedHashMap<>(cloudSdkCustomFields);
        if( id != null )
            declaredFields.put("id", id);
        if( type != null )
            declaredFields.put("type", type);
        if( function != null )
            declaredFields.put("function", function);
        return declaredFields;
    }

    /**
     * Set an unrecognizable property of this {@link MessageToolCall} instance. If the map previously contained a
     * mapping for the key, the old value is replaced by the specified value.
     *
     * @param customFieldName
     *            The name of the property
     * @param customFieldValue
     *            The value of the property
     */
    @JsonIgnore
    public void setCustomField( @Nonnull String customFieldName, @Nullable Object customFieldValue )
    {
        cloudSdkCustomFields.put(customFieldName, customFieldValue);
    }

    @Override
    public boolean equals( @Nullable final java.lang.Object o )
    {
        if( this == o ) {
            return true;
        }
        if( o == null || getClass() != o.getClass() ) {
            return false;
        }
        final MessageToolCall messageToolCall = (MessageToolCall) o;
        return Objects.equals(this.cloudSdkCustomFields, messageToolCall.cloudSdkCustomFields)
            && Objects.equals(this.id, messageToolCall.id)
            && Objects.equals(this.type, messageToolCall.type)
            && Objects.equals(this.function, messageToolCall.function);
    }

    @Override
    public int hashCode()
    {
        return Objects.hash(id, type, function, cloudSdkCustomFields);
    }

    @Override
    @Nonnull
    public String toString()
    {
        final StringBuilder sb = new StringBuilder();
        sb.append("class MessageToolCall {\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    type: ").append(toIndentedString(type)).append("\n");
        sb.append("    function: ").append(toIndentedString(function)).append("\n");
        cloudSdkCustomFields
            .forEach(( k, v ) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first line).
     */
    private String toIndentedString( final java.lang.Object o )
    {
        if( o == null ) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
