/*
 * Copyright (c) 2025 SAP SE or an SAP affiliate company. All rights reserved.
 */

/*
 * Prompt Registry API
 * Prompt Storage service for Design time & Runtime prompt templates.
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.cloud.sdk.datamodel.openapi.apache.sample.model;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.annotations.Beta;

/**
 * PromptTemplateSubstitutionResponse
 */

@Beta // CHECKSTYLE:OFF
public class PromptTemplateSubstitutionResponse
// CHECKSTYLE:ON
{
    @JsonProperty( "parsedPrompt" )
    private List<PromptTemplate> parsedPrompt = new ArrayList<>();

    @JsonProperty( "resource" )
    private PromptTemplateGetResponse resource;

    @JsonAnySetter
    @JsonAnyGetter
    private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

    /**
     * Default constructor for PromptTemplateSubstitutionResponse.
     */
    protected PromptTemplateSubstitutionResponse()
    {
    }

    /**
     * Set the parsedPrompt of this {@link PromptTemplateSubstitutionResponse} instance and return the same instance.
     *
     * @param parsedPrompt
     *            The parsedPrompt of this {@link PromptTemplateSubstitutionResponse}
     * @return The same instance of this {@link PromptTemplateSubstitutionResponse} class
     */
    @Nonnull
    public PromptTemplateSubstitutionResponse parsedPrompt( @Nullable final List<PromptTemplate> parsedPrompt )
    {
        this.parsedPrompt = parsedPrompt;
        return this;
    }

    /**
     * Add one parsedPrompt instance to this {@link PromptTemplateSubstitutionResponse}.
     *
     * @param parsedPromptItem
     *            The parsedPrompt that should be added
     * @return The same instance of type {@link PromptTemplateSubstitutionResponse}
     */
    @Nonnull
    public PromptTemplateSubstitutionResponse addParsedPromptItem( @Nonnull final PromptTemplate parsedPromptItem )
    {
        if( this.parsedPrompt == null ) {
            this.parsedPrompt = new ArrayList<>();
        }
        this.parsedPrompt.add(parsedPromptItem);
        return this;
    }

    /**
     * Get parsedPrompt
     *
     * @return parsedPrompt The parsedPrompt of this {@link PromptTemplateSubstitutionResponse} instance.
     */
    @Nonnull
    public List<PromptTemplate> getParsedPrompt()
    {
        return parsedPrompt;
    }

    /**
     * Set the parsedPrompt of this {@link PromptTemplateSubstitutionResponse} instance.
     *
     * @param parsedPrompt
     *            The parsedPrompt of this {@link PromptTemplateSubstitutionResponse}
     */
    public void setParsedPrompt( @Nullable final List<PromptTemplate> parsedPrompt )
    {
        this.parsedPrompt = parsedPrompt;
    }

    /**
     * Set the resource of this {@link PromptTemplateSubstitutionResponse} instance and return the same instance.
     *
     * @param resource
     *            The resource of this {@link PromptTemplateSubstitutionResponse}
     * @return The same instance of this {@link PromptTemplateSubstitutionResponse} class
     */
    @Nonnull
    public PromptTemplateSubstitutionResponse resource( @Nullable final PromptTemplateGetResponse resource )
    {
        this.resource = resource;
        return this;
    }

    /**
     * Get resource
     *
     * @return resource The resource of this {@link PromptTemplateSubstitutionResponse} instance.
     */
    @Nonnull
    public PromptTemplateGetResponse getResource()
    {
        return resource;
    }

    /**
     * Set the resource of this {@link PromptTemplateSubstitutionResponse} instance.
     *
     * @param resource
     *            The resource of this {@link PromptTemplateSubstitutionResponse}
     */
    public void setResource( @Nullable final PromptTemplateGetResponse resource )
    {
        this.resource = resource;
    }

    /**
     * Get the names of the unrecognizable properties of the {@link PromptTemplateSubstitutionResponse}.
     *
     * @return The set of properties names
     */
    @JsonIgnore
    @Nonnull
    public Set<String> getCustomFieldNames()
    {
        return cloudSdkCustomFields.keySet();
    }

    /**
     * Get the value of an unrecognizable property of this {@link PromptTemplateSubstitutionResponse} instance.
     *
     * @deprecated Use {@link #toMap()} instead.
     * @param name
     *            The name of the property
     * @return The value of the property
     * @throws NoSuchElementException
     *             If no property with the given name could be found.
     */
    @Nullable
    @Deprecated
    public Object getCustomField( @Nonnull final String name )
        throws NoSuchElementException
    {
        if( !cloudSdkCustomFields.containsKey(name) ) {
            throw new NoSuchElementException(
                "PromptTemplateSubstitutionResponse has no field with name '" + name + "'.");
        }
        return cloudSdkCustomFields.get(name);
    }

    /**
     * Get the value of all properties of this {@link PromptTemplateSubstitutionResponse} instance including
     * unrecognized properties.
     *
     * @return The map of all properties
     */
    @JsonIgnore
    @Nonnull
    public Map<String, Object> toMap()
    {
        final Map<String, Object> declaredFields = new LinkedHashMap<>(cloudSdkCustomFields);
        if( parsedPrompt != null )
            declaredFields.put("parsedPrompt", parsedPrompt);
        if( resource != null )
            declaredFields.put("resource", resource);
        return declaredFields;
    }

    /**
     * Set an unrecognizable property of this {@link PromptTemplateSubstitutionResponse} instance. If the map previously
     * contained a mapping for the key, the old value is replaced by the specified value.
     *
     * @param customFieldName
     *            The name of the property
     * @param customFieldValue
     *            The value of the property
     */
    @JsonIgnore
    public void setCustomField( @Nonnull String customFieldName, @Nullable Object customFieldValue )
    {
        cloudSdkCustomFields.put(customFieldName, customFieldValue);
    }

    @Override
    public boolean equals( @Nullable final java.lang.Object o )
    {
        if( this == o ) {
            return true;
        }
        if( o == null || getClass() != o.getClass() ) {
            return false;
        }
        final PromptTemplateSubstitutionResponse promptTemplateSubstitutionResponse =
            (PromptTemplateSubstitutionResponse) o;
        return Objects.equals(this.cloudSdkCustomFields, promptTemplateSubstitutionResponse.cloudSdkCustomFields)
            && Objects.equals(this.parsedPrompt, promptTemplateSubstitutionResponse.parsedPrompt)
            && Objects.equals(this.resource, promptTemplateSubstitutionResponse.resource);
    }

    @Override
    public int hashCode()
    {
        return Objects.hash(parsedPrompt, resource, cloudSdkCustomFields);
    }

    @Override
    @Nonnull
    public String toString()
    {
        final StringBuilder sb = new StringBuilder();
        sb.append("class PromptTemplateSubstitutionResponse {\n");
        sb.append("    parsedPrompt: ").append(toIndentedString(parsedPrompt)).append("\n");
        sb.append("    resource: ").append(toIndentedString(resource)).append("\n");
        cloudSdkCustomFields
            .forEach(( k, v ) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first line).
     */
    private String toIndentedString( final java.lang.Object o )
    {
        if( o == null ) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
