/*
 * Copyright (c) 2025 SAP SE or an SAP affiliate company. All rights reserved.
 */

/*
 * Prompt Registry API
 * Prompt Storage service for Design time & Runtime prompt templates.
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.cloud.sdk.datamodel.openapi.apache.sample.model;

import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.annotations.Beta;

/**
 * PromptTemplatingModuleConfig
 */

@Beta // CHECKSTYLE:OFF
public class PromptTemplatingModuleConfig
// CHECKSTYLE:ON
{
    @JsonProperty( "prompt" )
    private PromptTemplatingModuleConfigPrompt prompt;

    @JsonProperty( "model" )
    private LLMModelDetails model;

    @JsonAnySetter
    @JsonAnyGetter
    private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

    /**
     * Default constructor for PromptTemplatingModuleConfig.
     */
    protected PromptTemplatingModuleConfig()
    {
    }

    /**
     * Set the prompt of this {@link PromptTemplatingModuleConfig} instance and return the same instance.
     *
     * @param prompt
     *            The prompt of this {@link PromptTemplatingModuleConfig}
     * @return The same instance of this {@link PromptTemplatingModuleConfig} class
     */
    @Nonnull
    public PromptTemplatingModuleConfig prompt( @Nonnull final PromptTemplatingModuleConfigPrompt prompt )
    {
        this.prompt = prompt;
        return this;
    }

    /**
     * Get prompt
     *
     * @return prompt The prompt of this {@link PromptTemplatingModuleConfig} instance.
     */
    @Nonnull
    public PromptTemplatingModuleConfigPrompt getPrompt()
    {
        return prompt;
    }

    /**
     * Set the prompt of this {@link PromptTemplatingModuleConfig} instance.
     *
     * @param prompt
     *            The prompt of this {@link PromptTemplatingModuleConfig}
     */
    public void setPrompt( @Nonnull final PromptTemplatingModuleConfigPrompt prompt )
    {
        this.prompt = prompt;
    }

    /**
     * Set the model of this {@link PromptTemplatingModuleConfig} instance and return the same instance.
     *
     * @param model
     *            The model of this {@link PromptTemplatingModuleConfig}
     * @return The same instance of this {@link PromptTemplatingModuleConfig} class
     */
    @Nonnull
    public PromptTemplatingModuleConfig model( @Nonnull final LLMModelDetails model )
    {
        this.model = model;
        return this;
    }

    /**
     * Get model
     *
     * @return model The model of this {@link PromptTemplatingModuleConfig} instance.
     */
    @Nonnull
    public LLMModelDetails getModel()
    {
        return model;
    }

    /**
     * Set the model of this {@link PromptTemplatingModuleConfig} instance.
     *
     * @param model
     *            The model of this {@link PromptTemplatingModuleConfig}
     */
    public void setModel( @Nonnull final LLMModelDetails model )
    {
        this.model = model;
    }

    /**
     * Get the names of the unrecognizable properties of the {@link PromptTemplatingModuleConfig}.
     *
     * @return The set of properties names
     */
    @JsonIgnore
    @Nonnull
    public Set<String> getCustomFieldNames()
    {
        return cloudSdkCustomFields.keySet();
    }

    /**
     * Get the value of an unrecognizable property of this {@link PromptTemplatingModuleConfig} instance.
     *
     * @deprecated Use {@link #toMap()} instead.
     * @param name
     *            The name of the property
     * @return The value of the property
     * @throws NoSuchElementException
     *             If no property with the given name could be found.
     */
    @Nullable
    @Deprecated
    public Object getCustomField( @Nonnull final String name )
        throws NoSuchElementException
    {
        if( !cloudSdkCustomFields.containsKey(name) ) {
            throw new NoSuchElementException("PromptTemplatingModuleConfig has no field with name '" + name + "'.");
        }
        return cloudSdkCustomFields.get(name);
    }

    /**
     * Get the value of all properties of this {@link PromptTemplatingModuleConfig} instance including unrecognized
     * properties.
     *
     * @return The map of all properties
     */
    @JsonIgnore
    @Nonnull
    public Map<String, Object> toMap()
    {
        final Map<String, Object> declaredFields = new LinkedHashMap<>(cloudSdkCustomFields);
        if( prompt != null )
            declaredFields.put("prompt", prompt);
        if( model != null )
            declaredFields.put("model", model);
        return declaredFields;
    }

    /**
     * Set an unrecognizable property of this {@link PromptTemplatingModuleConfig} instance. If the map previously
     * contained a mapping for the key, the old value is replaced by the specified value.
     *
     * @param customFieldName
     *            The name of the property
     * @param customFieldValue
     *            The value of the property
     */
    @JsonIgnore
    public void setCustomField( @Nonnull String customFieldName, @Nullable Object customFieldValue )
    {
        cloudSdkCustomFields.put(customFieldName, customFieldValue);
    }

    @Override
    public boolean equals( @Nullable final java.lang.Object o )
    {
        if( this == o ) {
            return true;
        }
        if( o == null || getClass() != o.getClass() ) {
            return false;
        }
        final PromptTemplatingModuleConfig promptTemplatingModuleConfig = (PromptTemplatingModuleConfig) o;
        return Objects.equals(this.cloudSdkCustomFields, promptTemplatingModuleConfig.cloudSdkCustomFields)
            && Objects.equals(this.prompt, promptTemplatingModuleConfig.prompt)
            && Objects.equals(this.model, promptTemplatingModuleConfig.model);
    }

    @Override
    public int hashCode()
    {
        return Objects.hash(prompt, model, cloudSdkCustomFields);
    }

    @Override
    @Nonnull
    public String toString()
    {
        final StringBuilder sb = new StringBuilder();
        sb.append("class PromptTemplatingModuleConfig {\n");
        sb.append("    prompt: ").append(toIndentedString(prompt)).append("\n");
        sb.append("    model: ").append(toIndentedString(model)).append("\n");
        cloudSdkCustomFields
            .forEach(( k, v ) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first line).
     */
    private String toIndentedString( final java.lang.Object o )
    {
        if( o == null ) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
