/*
 * Copyright (c) 2025 SAP SE or an SAP affiliate company. All rights reserved.
 */

/*
 * Prompt Registry API
 * Prompt Storage service for Design time & Runtime prompt templates.
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.cloud.sdk.datamodel.openapi.apache.sample.model;

import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import java.util.UUID;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.annotations.Beta;

/**
 * PromptTemplatePostResponse
 */

@Beta // CHECKSTYLE:OFF
public class PromptTemplatePostResponse
// CHECKSTYLE:ON
{
    @JsonProperty( "message" )
    private String message;

    @JsonProperty( "id" )
    private UUID id;

    @JsonProperty( "scenario" )
    private String scenario;

    @JsonProperty( "name" )
    private String name;

    @JsonProperty( "version" )
    private String version;

    @JsonAnySetter
    @JsonAnyGetter
    private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

    /**
     * Default constructor for PromptTemplatePostResponse.
     */
    protected PromptTemplatePostResponse()
    {
    }

    /**
     * Set the message of this {@link PromptTemplatePostResponse} instance and return the same instance.
     *
     * @param message
     *            The message of this {@link PromptTemplatePostResponse}
     * @return The same instance of this {@link PromptTemplatePostResponse} class
     */
    @Nonnull
    public PromptTemplatePostResponse message( @Nonnull final String message )
    {
        this.message = message;
        return this;
    }

    /**
     * Get message
     *
     * @return message The message of this {@link PromptTemplatePostResponse} instance.
     */
    @Nonnull
    public String getMessage()
    {
        return message;
    }

    /**
     * Set the message of this {@link PromptTemplatePostResponse} instance.
     *
     * @param message
     *            The message of this {@link PromptTemplatePostResponse}
     */
    public void setMessage( @Nonnull final String message )
    {
        this.message = message;
    }

    /**
     * Set the id of this {@link PromptTemplatePostResponse} instance and return the same instance.
     *
     * @param id
     *            The id of this {@link PromptTemplatePostResponse}
     * @return The same instance of this {@link PromptTemplatePostResponse} class
     */
    @Nonnull
    public PromptTemplatePostResponse id( @Nonnull final UUID id )
    {
        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id The id of this {@link PromptTemplatePostResponse} instance.
     */
    @Nonnull
    public UUID getId()
    {
        return id;
    }

    /**
     * Set the id of this {@link PromptTemplatePostResponse} instance.
     *
     * @param id
     *            The id of this {@link PromptTemplatePostResponse}
     */
    public void setId( @Nonnull final UUID id )
    {
        this.id = id;
    }

    /**
     * Set the scenario of this {@link PromptTemplatePostResponse} instance and return the same instance.
     *
     * @param scenario
     *            The scenario of this {@link PromptTemplatePostResponse}
     * @return The same instance of this {@link PromptTemplatePostResponse} class
     */
    @Nonnull
    public PromptTemplatePostResponse scenario( @Nonnull final String scenario )
    {
        this.scenario = scenario;
        return this;
    }

    /**
     * Get scenario
     *
     * @return scenario The scenario of this {@link PromptTemplatePostResponse} instance.
     */
    @Nonnull
    public String getScenario()
    {
        return scenario;
    }

    /**
     * Set the scenario of this {@link PromptTemplatePostResponse} instance.
     *
     * @param scenario
     *            The scenario of this {@link PromptTemplatePostResponse}
     */
    public void setScenario( @Nonnull final String scenario )
    {
        this.scenario = scenario;
    }

    /**
     * Set the name of this {@link PromptTemplatePostResponse} instance and return the same instance.
     *
     * @param name
     *            The name of this {@link PromptTemplatePostResponse}
     * @return The same instance of this {@link PromptTemplatePostResponse} class
     */
    @Nonnull
    public PromptTemplatePostResponse name( @Nonnull final String name )
    {
        this.name = name;
        return this;
    }

    /**
     * Get name
     *
     * @return name The name of this {@link PromptTemplatePostResponse} instance.
     */
    @Nonnull
    public String getName()
    {
        return name;
    }

    /**
     * Set the name of this {@link PromptTemplatePostResponse} instance.
     *
     * @param name
     *            The name of this {@link PromptTemplatePostResponse}
     */
    public void setName( @Nonnull final String name )
    {
        this.name = name;
    }

    /**
     * Set the version of this {@link PromptTemplatePostResponse} instance and return the same instance.
     *
     * @param version
     *            The version of this {@link PromptTemplatePostResponse}
     * @return The same instance of this {@link PromptTemplatePostResponse} class
     */
    @Nonnull
    public PromptTemplatePostResponse version( @Nonnull final String version )
    {
        this.version = version;
        return this;
    }

    /**
     * Get version
     *
     * @return version The version of this {@link PromptTemplatePostResponse} instance.
     */
    @Nonnull
    public String getVersion()
    {
        return version;
    }

    /**
     * Set the version of this {@link PromptTemplatePostResponse} instance.
     *
     * @param version
     *            The version of this {@link PromptTemplatePostResponse}
     */
    public void setVersion( @Nonnull final String version )
    {
        this.version = version;
    }

    /**
     * Get the names of the unrecognizable properties of the {@link PromptTemplatePostResponse}.
     *
     * @return The set of properties names
     */
    @JsonIgnore
    @Nonnull
    public Set<String> getCustomFieldNames()
    {
        return cloudSdkCustomFields.keySet();
    }

    /**
     * Get the value of an unrecognizable property of this {@link PromptTemplatePostResponse} instance.
     *
     * @deprecated Use {@link #toMap()} instead.
     * @param name
     *            The name of the property
     * @return The value of the property
     * @throws NoSuchElementException
     *             If no property with the given name could be found.
     */
    @Nullable
    @Deprecated
    public Object getCustomField( @Nonnull final String name )
        throws NoSuchElementException
    {
        if( !cloudSdkCustomFields.containsKey(name) ) {
            throw new NoSuchElementException("PromptTemplatePostResponse has no field with name '" + name + "'.");
        }
        return cloudSdkCustomFields.get(name);
    }

    /**
     * Get the value of all properties of this {@link PromptTemplatePostResponse} instance including unrecognized
     * properties.
     *
     * @return The map of all properties
     */
    @JsonIgnore
    @Nonnull
    public Map<String, Object> toMap()
    {
        final Map<String, Object> declaredFields = new LinkedHashMap<>(cloudSdkCustomFields);
        if( message != null )
            declaredFields.put("message", message);
        if( id != null )
            declaredFields.put("id", id);
        if( scenario != null )
            declaredFields.put("scenario", scenario);
        if( name != null )
            declaredFields.put("name", name);
        if( version != null )
            declaredFields.put("version", version);
        return declaredFields;
    }

    /**
     * Set an unrecognizable property of this {@link PromptTemplatePostResponse} instance. If the map previously
     * contained a mapping for the key, the old value is replaced by the specified value.
     *
     * @param customFieldName
     *            The name of the property
     * @param customFieldValue
     *            The value of the property
     */
    @JsonIgnore
    public void setCustomField( @Nonnull String customFieldName, @Nullable Object customFieldValue )
    {
        cloudSdkCustomFields.put(customFieldName, customFieldValue);
    }

    @Override
    public boolean equals( @Nullable final java.lang.Object o )
    {
        if( this == o ) {
            return true;
        }
        if( o == null || getClass() != o.getClass() ) {
            return false;
        }
        final PromptTemplatePostResponse promptTemplatePostResponse = (PromptTemplatePostResponse) o;
        return Objects.equals(this.cloudSdkCustomFields, promptTemplatePostResponse.cloudSdkCustomFields)
            && Objects.equals(this.message, promptTemplatePostResponse.message)
            && Objects.equals(this.id, promptTemplatePostResponse.id)
            && Objects.equals(this.scenario, promptTemplatePostResponse.scenario)
            && Objects.equals(this.name, promptTemplatePostResponse.name)
            && Objects.equals(this.version, promptTemplatePostResponse.version);
    }

    @Override
    public int hashCode()
    {
        return Objects.hash(message, id, scenario, name, version, cloudSdkCustomFields);
    }

    @Override
    @Nonnull
    public String toString()
    {
        final StringBuilder sb = new StringBuilder();
        sb.append("class PromptTemplatePostResponse {\n");
        sb.append("    message: ").append(toIndentedString(message)).append("\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    scenario: ").append(toIndentedString(scenario)).append("\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    version: ").append(toIndentedString(version)).append("\n");
        cloudSdkCustomFields
            .forEach(( k, v ) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first line).
     */
    private String toIndentedString( final java.lang.Object o )
    {
        if( o == null ) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
