/*
 * Copyright (c) 2025 SAP SE or an SAP affiliate company. All rights reserved.
 */

/*
 * Prompt Registry API
 * Prompt Storage service for Design time & Runtime prompt templates.
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.cloud.sdk.datamodel.openapi.apache.sample.model;

import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.annotations.Beta;

/**
 * PromptTemplatePostRequest
 */

@Beta // CHECKSTYLE:OFF
public class PromptTemplatePostRequest
// CHECKSTYLE:ON
{
    @JsonProperty( "name" )
    private String name;

    @JsonProperty( "version" )
    private String version;

    @JsonProperty( "scenario" )
    private String scenario;

    @JsonProperty( "spec" )
    private PromptTemplateSpec spec;

    @JsonAnySetter
    @JsonAnyGetter
    private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

    /**
     * Default constructor for PromptTemplatePostRequest.
     */
    protected PromptTemplatePostRequest()
    {
    }

    /**
     * Set the name of this {@link PromptTemplatePostRequest} instance and return the same instance.
     *
     * @param name
     *            The name of this {@link PromptTemplatePostRequest}
     * @return The same instance of this {@link PromptTemplatePostRequest} class
     */
    @Nonnull
    public PromptTemplatePostRequest name( @Nonnull final String name )
    {
        this.name = name;
        return this;
    }

    /**
     * Get name
     *
     * @return name The name of this {@link PromptTemplatePostRequest} instance.
     */
    @Nonnull
    public String getName()
    {
        return name;
    }

    /**
     * Set the name of this {@link PromptTemplatePostRequest} instance.
     *
     * @param name
     *            The name of this {@link PromptTemplatePostRequest}
     */
    public void setName( @Nonnull final String name )
    {
        this.name = name;
    }

    /**
     * Set the version of this {@link PromptTemplatePostRequest} instance and return the same instance.
     *
     * @param version
     *            The version of this {@link PromptTemplatePostRequest}
     * @return The same instance of this {@link PromptTemplatePostRequest} class
     */
    @Nonnull
    public PromptTemplatePostRequest version( @Nonnull final String version )
    {
        this.version = version;
        return this;
    }

    /**
     * Get version
     *
     * @return version The version of this {@link PromptTemplatePostRequest} instance.
     */
    @Nonnull
    public String getVersion()
    {
        return version;
    }

    /**
     * Set the version of this {@link PromptTemplatePostRequest} instance.
     *
     * @param version
     *            The version of this {@link PromptTemplatePostRequest}
     */
    public void setVersion( @Nonnull final String version )
    {
        this.version = version;
    }

    /**
     * Set the scenario of this {@link PromptTemplatePostRequest} instance and return the same instance.
     *
     * @param scenario
     *            The scenario of this {@link PromptTemplatePostRequest}
     * @return The same instance of this {@link PromptTemplatePostRequest} class
     */
    @Nonnull
    public PromptTemplatePostRequest scenario( @Nonnull final String scenario )
    {
        this.scenario = scenario;
        return this;
    }

    /**
     * Get scenario
     *
     * @return scenario The scenario of this {@link PromptTemplatePostRequest} instance.
     */
    @Nonnull
    public String getScenario()
    {
        return scenario;
    }

    /**
     * Set the scenario of this {@link PromptTemplatePostRequest} instance.
     *
     * @param scenario
     *            The scenario of this {@link PromptTemplatePostRequest}
     */
    public void setScenario( @Nonnull final String scenario )
    {
        this.scenario = scenario;
    }

    /**
     * Set the spec of this {@link PromptTemplatePostRequest} instance and return the same instance.
     *
     * @param spec
     *            The spec of this {@link PromptTemplatePostRequest}
     * @return The same instance of this {@link PromptTemplatePostRequest} class
     */
    @Nonnull
    public PromptTemplatePostRequest spec( @Nonnull final PromptTemplateSpec spec )
    {
        this.spec = spec;
        return this;
    }

    /**
     * Get spec
     *
     * @return spec The spec of this {@link PromptTemplatePostRequest} instance.
     */
    @Nonnull
    public PromptTemplateSpec getSpec()
    {
        return spec;
    }

    /**
     * Set the spec of this {@link PromptTemplatePostRequest} instance.
     *
     * @param spec
     *            The spec of this {@link PromptTemplatePostRequest}
     */
    public void setSpec( @Nonnull final PromptTemplateSpec spec )
    {
        this.spec = spec;
    }

    /**
     * Get the names of the unrecognizable properties of the {@link PromptTemplatePostRequest}.
     *
     * @return The set of properties names
     */
    @JsonIgnore
    @Nonnull
    public Set<String> getCustomFieldNames()
    {
        return cloudSdkCustomFields.keySet();
    }

    /**
     * Get the value of an unrecognizable property of this {@link PromptTemplatePostRequest} instance.
     *
     * @deprecated Use {@link #toMap()} instead.
     * @param name
     *            The name of the property
     * @return The value of the property
     * @throws NoSuchElementException
     *             If no property with the given name could be found.
     */
    @Nullable
    @Deprecated
    public Object getCustomField( @Nonnull final String name )
        throws NoSuchElementException
    {
        if( !cloudSdkCustomFields.containsKey(name) ) {
            throw new NoSuchElementException("PromptTemplatePostRequest has no field with name '" + name + "'.");
        }
        return cloudSdkCustomFields.get(name);
    }

    /**
     * Get the value of all properties of this {@link PromptTemplatePostRequest} instance including unrecognized
     * properties.
     *
     * @return The map of all properties
     */
    @JsonIgnore
    @Nonnull
    public Map<String, Object> toMap()
    {
        final Map<String, Object> declaredFields = new LinkedHashMap<>(cloudSdkCustomFields);
        if( name != null )
            declaredFields.put("name", name);
        if( version != null )
            declaredFields.put("version", version);
        if( scenario != null )
            declaredFields.put("scenario", scenario);
        if( spec != null )
            declaredFields.put("spec", spec);
        return declaredFields;
    }

    /**
     * Set an unrecognizable property of this {@link PromptTemplatePostRequest} instance. If the map previously
     * contained a mapping for the key, the old value is replaced by the specified value.
     *
     * @param customFieldName
     *            The name of the property
     * @param customFieldValue
     *            The value of the property
     */
    @JsonIgnore
    public void setCustomField( @Nonnull String customFieldName, @Nullable Object customFieldValue )
    {
        cloudSdkCustomFields.put(customFieldName, customFieldValue);
    }

    @Override
    public boolean equals( @Nullable final java.lang.Object o )
    {
        if( this == o ) {
            return true;
        }
        if( o == null || getClass() != o.getClass() ) {
            return false;
        }
        final PromptTemplatePostRequest promptTemplatePostRequest = (PromptTemplatePostRequest) o;
        return Objects.equals(this.cloudSdkCustomFields, promptTemplatePostRequest.cloudSdkCustomFields)
            && Objects.equals(this.name, promptTemplatePostRequest.name)
            && Objects.equals(this.version, promptTemplatePostRequest.version)
            && Objects.equals(this.scenario, promptTemplatePostRequest.scenario)
            && Objects.equals(this.spec, promptTemplatePostRequest.spec);
    }

    @Override
    public int hashCode()
    {
        return Objects.hash(name, version, scenario, spec, cloudSdkCustomFields);
    }

    @Override
    @Nonnull
    public String toString()
    {
        final StringBuilder sb = new StringBuilder();
        sb.append("class PromptTemplatePostRequest {\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    version: ").append(toIndentedString(version)).append("\n");
        sb.append("    scenario: ").append(toIndentedString(scenario)).append("\n");
        sb.append("    spec: ").append(toIndentedString(spec)).append("\n");
        cloudSdkCustomFields
            .forEach(( k, v ) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first line).
     */
    private String toIndentedString( final java.lang.Object o )
    {
        if( o == null ) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
