/*
 * Copyright (c) 2025 SAP SE or an SAP affiliate company. All rights reserved.
 */

/*
 * Prompt Registry API
 * Prompt Storage service for Design time & Runtime prompt templates.
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.cloud.sdk.datamodel.openapi.apache.sample.model;

import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.google.common.annotations.Beta;

/**
 * Response format that the model output should adhere to. This is the same as the OpenAI definition. Compatible with
 * GPT-4o, GPT-4o mini, GPT-4 (Turbo) and all GPT-3.5 Turbo models newer than gpt-3.5-turbo-1106.
 */
@Beta
@JsonTypeInfo( use = JsonTypeInfo.Id.DEDUCTION )
@JsonSubTypes( {
    @JsonSubTypes.Type( value = ResponseFormatJsonObject.class ),
    @JsonSubTypes.Type( value = ResponseFormatJsonSchema.class ),
    @JsonSubTypes.Type( value = ResponseFormatText.class ), } )

public interface PromptTemplateSpecResponseFormat
{
}
