/*
 * Copyright (c) 2025 SAP SE or an SAP affiliate company. All rights reserved.
 */

/*
 * Prompt Registry API
 * Prompt Storage service for Design time & Runtime prompt templates.
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.cloud.sdk.datamodel.openapi.apache.sample.model;

import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.annotations.Beta;

/**
 * RuntimePromptTemplateFile
 */

@Beta // CHECKSTYLE:OFF
public class RuntimePromptTemplateFile
// CHECKSTYLE:ON
{
    @JsonProperty( "apiVersion" )
    private String apiVersion;

    @JsonProperty( "kind" )
    private String kind;

    @JsonProperty( "metadata" )
    private RuntimePromptTemplateFileMetadata metadata;

    @JsonProperty( "spec" )
    private PromptTemplateSpec spec;

    @JsonAnySetter
    @JsonAnyGetter
    private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

    /**
     * Default constructor for RuntimePromptTemplateFile.
     */
    protected RuntimePromptTemplateFile()
    {
    }

    /**
     * Set the apiVersion of this {@link RuntimePromptTemplateFile} instance and return the same instance.
     *
     * @param apiVersion
     *            The apiVersion of this {@link RuntimePromptTemplateFile}
     * @return The same instance of this {@link RuntimePromptTemplateFile} class
     */
    @Nonnull
    public RuntimePromptTemplateFile apiVersion( @Nullable final String apiVersion )
    {
        this.apiVersion = apiVersion;
        return this;
    }

    /**
     * Get apiVersion
     *
     * @return apiVersion The apiVersion of this {@link RuntimePromptTemplateFile} instance.
     */
    @Nonnull
    public String getApiVersion()
    {
        return apiVersion;
    }

    /**
     * Set the apiVersion of this {@link RuntimePromptTemplateFile} instance.
     *
     * @param apiVersion
     *            The apiVersion of this {@link RuntimePromptTemplateFile}
     */
    public void setApiVersion( @Nullable final String apiVersion )
    {
        this.apiVersion = apiVersion;
    }

    /**
     * Set the kind of this {@link RuntimePromptTemplateFile} instance and return the same instance.
     *
     * @param kind
     *            The kind of this {@link RuntimePromptTemplateFile}
     * @return The same instance of this {@link RuntimePromptTemplateFile} class
     */
    @Nonnull
    public RuntimePromptTemplateFile kind( @Nullable final String kind )
    {
        this.kind = kind;
        return this;
    }

    /**
     * Get kind
     *
     * @return kind The kind of this {@link RuntimePromptTemplateFile} instance.
     */
    @Nonnull
    public String getKind()
    {
        return kind;
    }

    /**
     * Set the kind of this {@link RuntimePromptTemplateFile} instance.
     *
     * @param kind
     *            The kind of this {@link RuntimePromptTemplateFile}
     */
    public void setKind( @Nullable final String kind )
    {
        this.kind = kind;
    }

    /**
     * Set the metadata of this {@link RuntimePromptTemplateFile} instance and return the same instance.
     *
     * @param metadata
     *            The metadata of this {@link RuntimePromptTemplateFile}
     * @return The same instance of this {@link RuntimePromptTemplateFile} class
     */
    @Nonnull
    public RuntimePromptTemplateFile metadata( @Nullable final RuntimePromptTemplateFileMetadata metadata )
    {
        this.metadata = metadata;
        return this;
    }

    /**
     * Get metadata
     *
     * @return metadata The metadata of this {@link RuntimePromptTemplateFile} instance.
     */
    @Nonnull
    public RuntimePromptTemplateFileMetadata getMetadata()
    {
        return metadata;
    }

    /**
     * Set the metadata of this {@link RuntimePromptTemplateFile} instance.
     *
     * @param metadata
     *            The metadata of this {@link RuntimePromptTemplateFile}
     */
    public void setMetadata( @Nullable final RuntimePromptTemplateFileMetadata metadata )
    {
        this.metadata = metadata;
    }

    /**
     * Set the spec of this {@link RuntimePromptTemplateFile} instance and return the same instance.
     *
     * @param spec
     *            The spec of this {@link RuntimePromptTemplateFile}
     * @return The same instance of this {@link RuntimePromptTemplateFile} class
     */
    @Nonnull
    public RuntimePromptTemplateFile spec( @Nullable final PromptTemplateSpec spec )
    {
        this.spec = spec;
        return this;
    }

    /**
     * Get spec
     *
     * @return spec The spec of this {@link RuntimePromptTemplateFile} instance.
     */
    @Nonnull
    public PromptTemplateSpec getSpec()
    {
        return spec;
    }

    /**
     * Set the spec of this {@link RuntimePromptTemplateFile} instance.
     *
     * @param spec
     *            The spec of this {@link RuntimePromptTemplateFile}
     */
    public void setSpec( @Nullable final PromptTemplateSpec spec )
    {
        this.spec = spec;
    }

    /**
     * Get the names of the unrecognizable properties of the {@link RuntimePromptTemplateFile}.
     *
     * @return The set of properties names
     */
    @JsonIgnore
    @Nonnull
    public Set<String> getCustomFieldNames()
    {
        return cloudSdkCustomFields.keySet();
    }

    /**
     * Get the value of an unrecognizable property of this {@link RuntimePromptTemplateFile} instance.
     *
     * @deprecated Use {@link #toMap()} instead.
     * @param name
     *            The name of the property
     * @return The value of the property
     * @throws NoSuchElementException
     *             If no property with the given name could be found.
     */
    @Nullable
    @Deprecated
    public Object getCustomField( @Nonnull final String name )
        throws NoSuchElementException
    {
        if( !cloudSdkCustomFields.containsKey(name) ) {
            throw new NoSuchElementException("RuntimePromptTemplateFile has no field with name '" + name + "'.");
        }
        return cloudSdkCustomFields.get(name);
    }

    /**
     * Get the value of all properties of this {@link RuntimePromptTemplateFile} instance including unrecognized
     * properties.
     *
     * @return The map of all properties
     */
    @JsonIgnore
    @Nonnull
    public Map<String, Object> toMap()
    {
        final Map<String, Object> declaredFields = new LinkedHashMap<>(cloudSdkCustomFields);
        if( apiVersion != null )
            declaredFields.put("apiVersion", apiVersion);
        if( kind != null )
            declaredFields.put("kind", kind);
        if( metadata != null )
            declaredFields.put("metadata", metadata);
        if( spec != null )
            declaredFields.put("spec", spec);
        return declaredFields;
    }

    /**
     * Set an unrecognizable property of this {@link RuntimePromptTemplateFile} instance. If the map previously
     * contained a mapping for the key, the old value is replaced by the specified value.
     *
     * @param customFieldName
     *            The name of the property
     * @param customFieldValue
     *            The value of the property
     */
    @JsonIgnore
    public void setCustomField( @Nonnull String customFieldName, @Nullable Object customFieldValue )
    {
        cloudSdkCustomFields.put(customFieldName, customFieldValue);
    }

    @Override
    public boolean equals( @Nullable final java.lang.Object o )
    {
        if( this == o ) {
            return true;
        }
        if( o == null || getClass() != o.getClass() ) {
            return false;
        }
        final RuntimePromptTemplateFile runtimePromptTemplateFile = (RuntimePromptTemplateFile) o;
        return Objects.equals(this.cloudSdkCustomFields, runtimePromptTemplateFile.cloudSdkCustomFields)
            && Objects.equals(this.apiVersion, runtimePromptTemplateFile.apiVersion)
            && Objects.equals(this.kind, runtimePromptTemplateFile.kind)
            && Objects.equals(this.metadata, runtimePromptTemplateFile.metadata)
            && Objects.equals(this.spec, runtimePromptTemplateFile.spec);
    }

    @Override
    public int hashCode()
    {
        return Objects.hash(apiVersion, kind, metadata, spec, cloudSdkCustomFields);
    }

    @Override
    @Nonnull
    public String toString()
    {
        final StringBuilder sb = new StringBuilder();
        sb.append("class RuntimePromptTemplateFile {\n");
        sb.append("    apiVersion: ").append(toIndentedString(apiVersion)).append("\n");
        sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
        sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
        sb.append("    spec: ").append(toIndentedString(spec)).append("\n");
        cloudSdkCustomFields
            .forEach(( k, v ) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first line).
     */
    private String toIndentedString( final java.lang.Object o )
    {
        if( o == null ) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
