/*
 * Copyright (c) 2025 SAP SE or an SAP affiliate company. All rights reserved.
 */

/*
 * Prompt Registry API
 * Prompt Storage service for Design time & Runtime prompt templates.
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.cloud.sdk.datamodel.openapi.apache.sample.model;

import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.annotations.Beta;

/**
 * SAPDocumentTranslationOutputConfig
 */

@Beta // CHECKSTYLE:OFF
public class SAPDocumentTranslationOutputConfig
// CHECKSTYLE:ON
{
    @JsonProperty( "source_language" )
    private String sourceLanguage;

    @JsonProperty( "target_language" )
    private SAPDocumentTranslationOutputTargetLanguage targetLanguage;

    @JsonAnySetter
    @JsonAnyGetter
    private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

    /**
     * Default constructor for SAPDocumentTranslationOutputConfig.
     */
    protected SAPDocumentTranslationOutputConfig()
    {
    }

    /**
     * Set the sourceLanguage of this {@link SAPDocumentTranslationOutputConfig} instance and return the same instance.
     *
     * @param sourceLanguage
     *            Language of the text to be translated.
     * @return The same instance of this {@link SAPDocumentTranslationOutputConfig} class
     */
    @Nonnull
    public SAPDocumentTranslationOutputConfig sourceLanguage( @Nullable final String sourceLanguage )
    {
        this.sourceLanguage = sourceLanguage;
        return this;
    }

    /**
     * Language of the text to be translated.
     *
     * @return sourceLanguage The sourceLanguage of this {@link SAPDocumentTranslationOutputConfig} instance.
     */
    @Nonnull
    public String getSourceLanguage()
    {
        return sourceLanguage;
    }

    /**
     * Set the sourceLanguage of this {@link SAPDocumentTranslationOutputConfig} instance.
     *
     * @param sourceLanguage
     *            Language of the text to be translated.
     */
    public void setSourceLanguage( @Nullable final String sourceLanguage )
    {
        this.sourceLanguage = sourceLanguage;
    }

    /**
     * Set the targetLanguage of this {@link SAPDocumentTranslationOutputConfig} instance and return the same instance.
     *
     * @param targetLanguage
     *            The targetLanguage of this {@link SAPDocumentTranslationOutputConfig}
     * @return The same instance of this {@link SAPDocumentTranslationOutputConfig} class
     */
    @Nonnull
    public SAPDocumentTranslationOutputConfig targetLanguage(
        @Nonnull final SAPDocumentTranslationOutputTargetLanguage targetLanguage )
    {
        this.targetLanguage = targetLanguage;
        return this;
    }

    /**
     * Get targetLanguage
     *
     * @return targetLanguage The targetLanguage of this {@link SAPDocumentTranslationOutputConfig} instance.
     */
    @Nonnull
    public SAPDocumentTranslationOutputTargetLanguage getTargetLanguage()
    {
        return targetLanguage;
    }

    /**
     * Set the targetLanguage of this {@link SAPDocumentTranslationOutputConfig} instance.
     *
     * @param targetLanguage
     *            The targetLanguage of this {@link SAPDocumentTranslationOutputConfig}
     */
    public void setTargetLanguage( @Nonnull final SAPDocumentTranslationOutputTargetLanguage targetLanguage )
    {
        this.targetLanguage = targetLanguage;
    }

    /**
     * Get the names of the unrecognizable properties of the {@link SAPDocumentTranslationOutputConfig}.
     *
     * @return The set of properties names
     */
    @JsonIgnore
    @Nonnull
    public Set<String> getCustomFieldNames()
    {
        return cloudSdkCustomFields.keySet();
    }

    /**
     * Get the value of an unrecognizable property of this {@link SAPDocumentTranslationOutputConfig} instance.
     *
     * @deprecated Use {@link #toMap()} instead.
     * @param name
     *            The name of the property
     * @return The value of the property
     * @throws NoSuchElementException
     *             If no property with the given name could be found.
     */
    @Nullable
    @Deprecated
    public Object getCustomField( @Nonnull final String name )
        throws NoSuchElementException
    {
        if( !cloudSdkCustomFields.containsKey(name) ) {
            throw new NoSuchElementException(
                "SAPDocumentTranslationOutputConfig has no field with name '" + name + "'.");
        }
        return cloudSdkCustomFields.get(name);
    }

    /**
     * Get the value of all properties of this {@link SAPDocumentTranslationOutputConfig} instance including
     * unrecognized properties.
     *
     * @return The map of all properties
     */
    @JsonIgnore
    @Nonnull
    public Map<String, Object> toMap()
    {
        final Map<String, Object> declaredFields = new LinkedHashMap<>(cloudSdkCustomFields);
        if( sourceLanguage != null )
            declaredFields.put("sourceLanguage", sourceLanguage);
        if( targetLanguage != null )
            declaredFields.put("targetLanguage", targetLanguage);
        return declaredFields;
    }

    /**
     * Set an unrecognizable property of this {@link SAPDocumentTranslationOutputConfig} instance. If the map previously
     * contained a mapping for the key, the old value is replaced by the specified value.
     *
     * @param customFieldName
     *            The name of the property
     * @param customFieldValue
     *            The value of the property
     */
    @JsonIgnore
    public void setCustomField( @Nonnull String customFieldName, @Nullable Object customFieldValue )
    {
        cloudSdkCustomFields.put(customFieldName, customFieldValue);
    }

    @Override
    public boolean equals( @Nullable final java.lang.Object o )
    {
        if( this == o ) {
            return true;
        }
        if( o == null || getClass() != o.getClass() ) {
            return false;
        }
        final SAPDocumentTranslationOutputConfig saPDocumentTranslationOutputConfig =
            (SAPDocumentTranslationOutputConfig) o;
        return Objects.equals(this.cloudSdkCustomFields, saPDocumentTranslationOutputConfig.cloudSdkCustomFields)
            && Objects.equals(this.sourceLanguage, saPDocumentTranslationOutputConfig.sourceLanguage)
            && Objects.equals(this.targetLanguage, saPDocumentTranslationOutputConfig.targetLanguage);
    }

    @Override
    public int hashCode()
    {
        return Objects.hash(sourceLanguage, targetLanguage, cloudSdkCustomFields);
    }

    @Override
    @Nonnull
    public String toString()
    {
        final StringBuilder sb = new StringBuilder();
        sb.append("class SAPDocumentTranslationOutputConfig {\n");
        sb.append("    sourceLanguage: ").append(toIndentedString(sourceLanguage)).append("\n");
        sb.append("    targetLanguage: ").append(toIndentedString(targetLanguage)).append("\n");
        cloudSdkCustomFields
            .forEach(( k, v ) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first line).
     */
    private String toIndentedString( final java.lang.Object o )
    {
        if( o == null ) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
