name: 'Blackduck Scan'

on:
  workflow_dispatch:
  schedule:
    - cron: 0 23 * * *

permissions: {}

jobs:
  scan:
    name: "Blackduck Scan"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v7
        with:
          ref: cve-fixing
      - name: "Scan With Black Duck"
        uses: ./.github/actions/scan-with-blackduck
        with:
          token: ${{ secrets.BLACKDUCK_TOKEN }}

