name: 'Blackduck Scan'

on:
  workflow_dispatch:
  schedule:
    - cron: 0 23 * * *

jobs:
  scan:
    name: "Blackduck Scan"
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - name: "Scan With Black Duck"
        uses: ./.github/actions/scan-with-blackduck
        with:
          token: ${{ secrets.BLACKDUCK_TOKEN }}

  notify-job:
    runs-on: ubuntu-latest
    needs: [ scan ]
    if: ${{ failure() && github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Notify
        run: python .pipeline/scripts/notify.py
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          WORKFLOW: ${{ github.workflow }}
          WORKFLOW_RUN_URL: https://github.com/SAP/cloud-sdk-java/actions/runs/${{ github.run_id }}
          BRANCH_NAME: ${{ github.ref_name }}
