name: "Pull Request Build"

on:
  pull_request:
    branches: [ "main" ]

env:
  CI_BUILD_WORKFLOW: "ci.yaml" # Name of the workflow that should be triggered for CI builds
  COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
  BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
  BRANCH_REF: refs/heads/${{ github.event.pull_request.head.ref }}

jobs:
  run-ci:
    runs-on: ubuntu-latest
    name: Continuous Integration
    permissions:
      actions: write # needed to trigger the ci workflow
      statuses: write # needed to update the commit status
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Trigger CI Workflow
        id: trigger-ci
        uses: ./.github/actions/trigger-workflow
        with:
          workflow: ${{ env.CI_BUILD_WORKFLOW }}
          workflow-ref: ${{ env.BRANCH_NAME }}
          commit-sha: ${{ env.COMMIT_SHA }}
          parameters: >
            -f repository-version=${{ env.BRANCH_REF }} 
            -f create-release-artifacts=false 
            -f check-blackduck=false

      - name: Await CI Workflow
        id: await-ci
        uses: ./.github/actions/await-workflow
        with:
          run-id: ${{ steps.trigger-ci.outputs.run-id }}
          commit-status: "Continuous Integration Workflow"
