name: Test push to protected branch

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: 'improve-release'
          fetch-depth: '0'

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: maven

      - run: |
          git push protected-test

        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
