name: Test maven deploy file

on:
  workflow_dispatch:
  push:
    branches: [improve-perform-release]

env:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.color=false"
  MVN_CLI_ARGS: "--batch-mode --no-transfer-progress --fail-at-end --show-version"
  MVN_SKIP_ARGS: "-DskipFormatting -Denforcer.skip -Djacoco.skip -Dmdep.analyze.skip"

jobs:
  deploy-file:
    name: Test Deploy File
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          server-id: artifactory-snapshots
          server-username: ARTIFACTORY_USER # env variable for username in deploy
          server-password: ARTIFACTORY_TOKEN # env variable for token in deploy
      - name: Deploy to local repo
        run: >
          mvn $MVN_CLI_ARGS -DskipTests package
          
          mkdir -p release/artifacts
          
          find . -path '**/target/*.jar' -exec cp --parents {} ./release/artifacts \;
          
          find . -path '**/pom.xml' -exec cp --parents {} ./release/artifacts \;
          
          python .pipeline/scripts/generate-pom.py --version 0.0.1-SNAPSHOT --pomFile ./release/pom.xml

          zip -q -r sap-cloud-sdk-java-v0.0.1.zip ./release

      - name: Upload Test Release
        uses: actions/upload-artifact@v3
        with:
          name: release-zip
          path: sap-cloud-sdk-java-v0.0.1.zip
          retention-days: 1

      - name: Deploy to artifactory
        working-directory: ./release
        run: >
          mvn
          $MVN_CLI_ARGS
          -DaltDeploymentRepository=artifactory-snapshots::https://common.repositories.cloud.sap/artifactory/build-snapshots-cloudsdk
          -Durl=https://common.repositories.cloud.sap/artifactory/build-snapshots-cloudsdk
          -DrepositoryId=artifactory-snapshots
          deploy

          # mvn
          # -Durl=artifactory-snapshots::https://common.repositories.cloud.sap/artifactory/build-snapshots-cloudsdk
          # -Dfile=$JAR_PATH
          # -Dfiles=./v0.0.1/cloud-sdk-core-0.0.1.jar
          # -Dtypes=jar
          # -Dclassifiers=bin
          # deploy:deploy-file

        env:
          ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
          ARTIFACTORY_TOKEN: ${{ secrets.ARTIFACTORY_TOKEN }}
