name: Test maven deploy file

on:
  workflow_dispatch:
  push:
    branches: [improve-perform-release]

env:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.color=false"
  MVN_CLI_ARGS: "--batch-mode --no-transfer-progress --fail-at-end --show-version"
  MVN_SKIP_ARGS: "-DskipFormatting -Denforcer.skip -Djacoco.skip -Dmdep.analyze.skip"

jobs:
  deploy-file:
    name: Test Deploy File
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          server-id: artifactory-snapshots
          server-username: ARTIFACTORY_USER # env variable for username in deploy
          server-password: ARTIFACTORY_TOKEN # env variable for token in deploy
      - name: Deploy File
        run: >
          mvn $MVN_CLI_ARGS -DskipTests install org.apache.maven.plugins:maven-deploy-plugin:3.1.1:deploy -DaltDeploymentRepository=local::file:./v0.0.1

          mvn
          -Durl=artifactory-snapshots::https://common.repositories.cloud.sap/artifactory/build-snapshots-cloudsdk
          -Dfile=./v0.0.1/com/sap/cloud/sdk/datamodel/fluent-result/0.0.1-SNAPSHOT/fluent-result-0.0.1-SNAPSHOT.jar
          -Dfiles=./v0.0.1/cloud-sdk-core-0.0.1.jar
          deploy:deploy-file

        env:
          ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
          ARTIFACTORY_TOKEN: ${{ secrets.ARTIFACTORY_TOKEN }}
